/**
 * @file Customer Care Policy Registry and Payload Field Allowlist (implement/04 §3.2, implement/08 §1.2).
 *
 * Invariant:
 * Contains the canonical PolicyRegistrySkill definitions and allowed payload fields for Customer Care.
 */

import type { PolicyRegistrySkill } from '@agentos/core-engine';

/** Allowed fields in action payloads per Care skill, using static Record lookup */
export const CARE_ALLOWED_PAYLOAD_FIELDS: Readonly<Record<string, Readonly<Record<string, true>>>> = Object.freeze({
  'skill.care.lookup_order': Object.freeze({
    order_id: true,
    order_identifier: true,
    customer_id: true,
    verification_reference: true,
    verification_status: true,
    tenant_id: true,
    effect_key: true,
  }),
  'skill.care.search_faq': Object.freeze({
    query: true,
    query_text: true,
    category: true,
    top_k: true,
    limit: true,
    tenant_id: true,
    effect_key: true,
  }),
  'skill.care.track_shipping': Object.freeze({
    tracking_number: true,
    carrier: true,
    order_identifier: true,
    order_id: true,
    customer_id: true,
    tenant_id: true,
    effect_key: true,
  }),
  'skill.care.manage_case': Object.freeze({
    action: true,
    case_id: true,
    customer_id: true,
    priority: true,
    notes: true,
    tenant_id: true,
    effect_key: true,
  }),
  'skill.care.initiate_return': Object.freeze({
    order_identifier: true,
    order_id: true,
    customer_id: true,
    items: true,
    reason: true,
    tenant_id: true,
    effect_key: true,
  }),
  'skill.care.escalate_to_human': Object.freeze({
    tenant_id: true,
    session_id: true,
    conversation_id: true,
    customer_id: true,
    escalation_reason: true,
    summary_context: true,
    effect_key: true,
  }),
  'skill.care.analyze_churn_risk': Object.freeze({
    customer_id: true,
    signals: true,
    tenant_id: true,
    effect_key: true,
  }),
  'skill.care.issue_retention_offer': Object.freeze({
    customer_id: true,
    offer_type: true,
    discount_rate: true,
    catalog_ref_id: true,
    proposed_price: true,
    tenant_id: true,
    effect_key: true,
  }),
});

/** Canonical skill definitions for Customer Care from packages/skills/src/platform/care/*.ts */
export const CARE_SKILLS: Readonly<Record<string, PolicyRegistrySkill>> = Object.freeze({
  'skill.care.lookup_order': {
    skill_id: 'skill.care.lookup_order',
    allowed_agents: Object.freeze(['CS-01']),
    required_authority: 'AUTH-0',
    mutating: false,
    price_bearing: false,
    idempotent: true,
    epistemic_class: 'FACT',
    write_target: 'HYPOTHESIS',
    requires_consent: false,
    requires_verified_identity: true,
    timeout_ms: 2000,
  },
  'skill.care.search_faq': {
    skill_id: 'skill.care.search_faq',
    allowed_agents: Object.freeze(['CS-01']),
    required_authority: 'AUTH-0',
    mutating: false,
    price_bearing: false,
    idempotent: true,
    epistemic_class: 'FACT',
    write_target: 'HYPOTHESIS',
    requires_consent: false,
    requires_verified_identity: false,
    timeout_ms: 1500,
  },
  'skill.care.track_shipping': {
    skill_id: 'skill.care.track_shipping',
    allowed_agents: Object.freeze(['CS-01']),
    required_authority: 'AUTH-0',
    mutating: false,
    price_bearing: false,
    idempotent: true,
    epistemic_class: 'FACT',
    write_target: 'HYPOTHESIS',
    requires_consent: false,
    requires_verified_identity: true,
    timeout_ms: 2000,
  },
  'skill.care.manage_case': {
    skill_id: 'skill.care.manage_case',
    allowed_agents: Object.freeze(['CS-01']),
    required_authority: 'AUTH-3',
    mutating: true,
    price_bearing: false,
    idempotent: false,
    epistemic_class: 'FACT',
    write_target: 'FACT',
    requires_consent: false,
    requires_verified_identity: true,
    timeout_ms: 3000,
  },
  'skill.care.initiate_return': {
    skill_id: 'skill.care.initiate_return',
    allowed_agents: Object.freeze(['CS-01']),
    required_authority: 'AUTH-4',
    mutating: true,
    price_bearing: false,
    idempotent: false,
    epistemic_class: 'FACT',
    write_target: 'FACT',
    requires_consent: false,
    requires_verified_identity: true,
    timeout_ms: 3000,
  },
  'skill.care.escalate_to_human': {
    skill_id: 'skill.care.escalate_to_human',
    allowed_agents: Object.freeze(['CS-01', 'CS-02']),
    required_authority: 'AUTH-3',
    mutating: true,
    price_bearing: false,
    idempotent: false,
    epistemic_class: 'FACT',
    write_target: 'FACT',
    requires_consent: false,
    requires_verified_identity: false,
    timeout_ms: 2000,
  },
  'skill.care.analyze_churn_risk': {
    skill_id: 'skill.care.analyze_churn_risk',
    allowed_agents: Object.freeze(['CS-02']),
    required_authority: 'AUTH-1',
    mutating: false,
    price_bearing: false,
    idempotent: true,
    epistemic_class: 'HYPOTHESIS',
    write_target: 'HYPOTHESIS',
    requires_consent: false,
    requires_verified_identity: true,
    timeout_ms: 2500,
  },
  'skill.care.issue_retention_offer': {
    skill_id: 'skill.care.issue_retention_offer',
    allowed_agents: Object.freeze(['CS-02']),
    required_authority: 'AUTH-3',
    mutating: true,
    price_bearing: true,
    idempotent: false,
    epistemic_class: 'DECISION',
    write_target: 'FACT',
    requires_consent: true,
    requires_verified_identity: true,
    timeout_ms: 3000,
  },
});
