"""Generate the acceptance-spec documents of testcases/ from the case sources.

    python testcases/_generate.py            # validate sources, then write generated output
    python testcases/_generate.py --check    # validate + compare with disk, write nothing

The authoritative case content lives in testcases/sources/{business,governance,platform}.py
(each exports CASES: list[dict] and FIXTURES: dict[str, json-serializable]) and the
requirement inventory lives in testcases/sources/requirements.json. Everything else under
testcases/ is generated by this file and must not be hand-edited: this generator never writes
_generate.py, sources/*.py, sources/requirements.json or sources/baseline-ids.json.

Output families: unit/, integration/, e2e/ and governance/ case documents (one per suite the
sources declare), the derived guides README.md, TRACEABILITY.md, COVERAGE.md and the
platform/ knowledge-memory + entity coverage maps, the fixtures (source FIXTURES plus a
secret-free fixtures/live/env.example and the guide files), one JSON export per case under
fixtures/scenarios/, and manifest.json with counts, coverage and SHA-256 input hashes.

Stdlib only, offline, deterministic: no timestamps, no randomness, no network, no hidden state.
Every generated file is written through a temporary file and an atomic replace, and only after
all validation passed. Generation proves document integrity, reference validity and coverage
bookkeeping only - never system behaviour. The repository runtime includes an API, a worker with
Care/Sales/Marketing agents, Tenant Console, Platform Admin, and PostgreSQL migrations. These
acceptance specifications are not runtime results: every case remains NOT_RUN unless separately
executed, and this generator never records PASS.
"""

from __future__ import annotations

import argparse

if __package__:
    from .generators.model import *
    from .generators.inputs import *
    from .generators.validation import *
    from .generators.render import *
    from .generators.output import *
else:
    try:
        from generators.model import *
        from generators.inputs import *
        from generators.validation import *
        from generators.render import *
        from generators.output import *
    except ModuleNotFoundError:
        from testcases.generators.model import *
        from testcases.generators.inputs import *
        from testcases.generators.validation import *
        from testcases.generators.render import *
        from testcases.generators.output import *

def report(problems: Problems) -> None:
    for warning in problems.warnings:
        print(f"WARN: {warning}")
    for error in problems.errors:
        print(f"ERROR: {error}")
    print(f"validation: {len(problems.errors)} error(s), {len(problems.warnings)} warning(s)")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        prog="python testcases/_generate.py",
        description="Validate the testcase sources and generate the testcases documents, fixtures and manifest.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate and compare generated output with disk; write nothing",
    )
    args = parser.parse_args(argv)

    problems = Problems()
    try:
        inv = load_inventory()
        baseline = load_baseline()
        modules = load_modules()
    except GenerateError as exc:
        print(f"ERROR: {exc}")
        return 2

    cases = collect_cases(modules, problems)
    fixtures = collect_fixtures(modules, problems)

    fixture_paths = set(fixtures) | {LIVE_ENV_EXAMPLE, FIXTURES_GUIDE, LIVE_FIXTURES_GUIDE}
    for case in cases:
        validate_case(case, problems, inv, fixture_paths)

    by_id = validate_ids(cases, problems)
    baseline_info = validate_baseline(cases, baseline, problems)
    pairs = validate_pairs(cases, by_id, problems)
    both_env = validate_both_environments(cases, inv, problems)
    coverage = build_coverage(cases, inv)

    for token in coverage["facet_gaps"]:
        problems.error(f"mandatory facet token {token!r} is not covered by any case")
    for token in coverage["requirement_gaps"]:
        problems.warn(f"requirement token {token!r} is not claimed by any case (reported as a coverage gap)")

    report(problems)
    if not problems.ok:
        print(
            f"FAILED: {len(problems.errors)} validation error(s); nothing was written and no generated "
            "file was touched"
        )
        return 2

    summary = [
        f"cases: {len(cases)} from {len(modules)} source module(s) "
        f"({', '.join(f'sources/{name}.py' for name in MODULES)})",
        "layers: " + ", ".join(f"{layer} {sum(1 for c in cases if c['layer'] == layer)}" for layer in LAYER_DIRS),
        "environments: " + ", ".join(
            f"{env} {sum(1 for c in cases if c['environment'] == env)}" for env in ENVIRONMENTS
        ),
        f"baseline: {baseline_info['preserved']}/{baseline_info['count']} current IDs preserved exactly once"
        f" (+{baseline_info['new_case_count']} new descriptive IDs)",
        f"e2e pairs: {pairs['paired_e2e_cases']}/{pairs['e2e_cases']} paired offline/live",
        f"coverage: requirements {sum(1 for ids in coverage['requirement_cases'].values() if ids)}"
        f"/{len(coverage['requirement_cases'])}, facets "
        f"{sum(1 for ids in coverage['facet_cases'].values() if ids)}/{len(coverage['facet_cases'])}",
    ]

    outputs = build_outputs(
        cases,
        fixtures,
        inv,
        baseline_info,
        coverage,
        pairs,
        both_env,
        problems,
        fixture_owners(modules),
    )

    if args.check:
        status = check_outputs(outputs)
        for line in summary:
            print(line)
        print("--check wrote nothing and mutated nothing")
        return status

    try:
        written = write_outputs(outputs)
    except GenerateError as exc:
        print(f"ERROR: {exc}")
        return 2

    for line in summary:
        print(line)
    print(f"wrote {len(written)} file(s) under testcases/; every case stays {DEFAULT_STATUS}")

    leftovers = stale_extras(outputs)
    if leftovers:
        print(
            f"NOTE: {len(leftovers)} generated-looking file(s) on disk are not produced by this run and "
            "were left untouched (delete or regenerate them deliberately):"
        )
        for rel in leftovers:
            print(f"  testcases/{rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
