"""Generate the acceptance-spec documents of testcases/ from the case sources.

    python testcases/_generate.py            # validate sources, then write generated output
    python testcases/_generate.py --check    # validate + compare with disk, write nothing

The authoritative case content lives in testcases/sources/{business,governance,platform}.py
(each exports CASES: list[dict] and FIXTURES: dict[str, json-serializable]) and the
requirement inventory lives in testcases/sources/requirements.json. Everything else under
testcases/ is generated by this file and must not be hand-edited: this generator never writes
_generate.py, sources/*.py, sources/requirements.json or sources/baseline-ids.json.

Output families: unit/, integration/, e2e/ and governance/ case documents (one per suite the
sources declare), the derived guides README.md, TRACEABILITY.md, COVERAGE.md and the
platform/ knowledge-memory + entity coverage maps, the fixtures (source FIXTURES plus a
secret-free fixtures/live/env.example and the guide files), one JSON export per case under
fixtures/scenarios/, and manifest.json with counts, coverage and SHA-256 input hashes.

Stdlib only, offline, deterministic: no timestamps, no randomness, no network, no hidden state.
Every generated file is written through a temporary file and an atomic replace, and only after
all validation passed. Generation proves document integrity, reference validity and coverage
bookkeeping only - never system behaviour. There is no application runtime in this repository,
so every case is reported NOT_RUN and this generator never records PASS.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
import re
import sys
from collections import Counter, OrderedDict
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
SOURCES = HERE / "sources"
MODULES = ("business", "governance", "platform")
REQUIREMENTS_REL = "sources/requirements.json"
BASELINE_REL = "sources/baseline-ids.json"
GENERATOR_REL = "testcases/_generate.py"
SRS_REL = "De_bai_Xay_dung_He_thong_AI_Agent_Marketing_Sales_CSKH_v0.1.md"

# Files this generator must never create or overwrite: they are hand-written inputs.
SOURCE_OWNED = (
    "_generate.py",
    REQUIREMENTS_REL,
    BASELINE_REL,
    *(f"sources/{name}.py" for name in MODULES),
)

LAYER_DIRS = ("unit", "integration", "e2e", "governance")
SUITE_RE = re.compile(r"^(unit|integration|e2e|governance)/[A-Za-z0-9][A-Za-z0-9._/-]*\.md$")
CASE_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")
ENVIRONMENTS = ("offline", "live")
PRIORITIES = ("critical", "high", "medium")
GATES = ("P0", "P1", "P2", "P3", "P4", "P5")
BASES = ("baseline", "blueprint", "extension")

MINIMUMS = {"preconditions": 2, "steps": 3, "assertions": 3, "forbidden": 2, "evidence": 2, "cleanup": 1}
E2E_RECOMMENDED_STEPS = 6

# The full case contract; 'pair' is additionally allowed (and mandatory for e2e cases).
REQUIRED_FIELDS = (
    "id",
    "title",
    "suite",
    "layer",
    "environment",
    "priority",
    "gate",
    "basis",
    "requirements",
    "facets",
    "references",
    "risk",
    "fixtures",
    "preconditions",
    "inputs",
    "steps",
    "assertions",
    "forbidden",
    "evidence",
    "cleanup",
    "automation",
    "prerequisites",
)

SCENARIO_DIR = "fixtures/scenarios"
LIVE_ENV_EXAMPLE = "fixtures/live/env.example"
FIXTURES_GUIDE = "fixtures/README.md"
LIVE_FIXTURES_GUIDE = "fixtures/live/README.md"

# The nine system acceptance criteria (SRS section 22) and the four independent pilots
# (section 21) must each be represented in BOTH environments, in the inventory and in cases.
E2E_CRITERIA = tuple(f"TC-E2E-{index:03d}" for index in range(1, 10))
PILOT_CRITERIA = tuple(f"PILOT-{index:02d}" for index in range(1, 5))

# Generated platform-level coverage maps (facet families -> covering cases). They are
# derived documents, not case suites: no case may declare a suite under platform/.
PLATFORM_DIR = "platform"
PLATFORM_KNOWLEDGE_DOC = f"{PLATFORM_DIR}/knowledge-memory.md"
PLATFORM_ENTITIES_DOC = f"{PLATFORM_DIR}/entities.md"
PLATFORM_FACET_FAMILIES = ("kb", "memory", "entity")
DERIVED_DOCS = (
    "README.md",
    "TRACEABILITY.md",
    "COVERAGE.md",
    PLATFORM_KNOWLEDGE_DOC,
    PLATFORM_ENTITIES_DOC,
    FIXTURES_GUIDE,
    LIVE_FIXTURES_GUIDE,
    LIVE_ENV_EXAMPLE,
    "manifest.json",
)

# Every generator input is hashed into manifest.json so a review can pin exactly which
# sources produced the documents.
HASHED_INPUTS = (GENERATOR_REL, SRS_REL, "testcases/sources/requirements.json", "testcases/sources/baseline-ids.json")

STATUS_VOCAB = [
    "NOT_RUN",
    "PASS",
    "FAIL",
    "SKIP_ASM_001",
    "SKIP_UNIMPLEMENTED",
    "BLOCKED_PREREQUISITE",
]
DEFAULT_STATUS = "NOT_RUN"

PROTECTED_SUFFIXES = (".local", ".secret", ".key", ".pem", ".env")
PROTECTED_NAMES = ("env.local", "credentials.json", "secrets.json", "results.json")
PROTECTED_PARTS = ("results",)

EMAIL_RE = re.compile(r"[A-Za-z0-9._%+-]+@([A-Za-z0-9.-]+\.[A-Za-z]{2,})")
PHONE_RE = re.compile(r"\+\d[\d\s().-]{5,}\d")


class GenerateError(Exception):
    """Fatal, non-recoverable condition (missing file, unreadable source module)."""


class Problems:
    """Collected validation findings. Errors block generation; warnings do not."""

    def __init__(self) -> None:
        self.errors: list[str] = []
        self.warnings: list[str] = []

    def error(self, message: str) -> None:
        self.errors.append(message)

    def warn(self, message: str) -> None:
        self.warnings.append(message)

    @property
    def ok(self) -> bool:
        return not self.errors


# --------------------------------------------------------------------------------------
# inventory
# --------------------------------------------------------------------------------------


class Inventory:
    """Requirement IDs, section aliases and mandatory facet tokens from requirements.json."""

    def __init__(self, doc: dict) -> None:
        self.doc = doc
        self.requirements: dict[str, dict] = dict(doc.get("requirements") or {})
        self.aliases: dict[str, dict] = dict(doc.get("aliases") or {})
        self.facets: dict[str, dict] = {}
        for family, spec in (doc.get("facets") or {}).items():
            items = {}
            for item in spec.get("items") or []:
                token = item.get("token")
                if not isinstance(token, str) or not token:
                    raise GenerateError(
                        f"requirements.json: facet family '{family}' has an item without a token"
                    )
                items[token] = item
            self.facets[family] = {
                "description": spec.get("description", ""),
                "srs_section": spec.get("srs_section", ""),
                "mandatory": bool(spec.get("mandatory", True)),
                "items": items,
            }

    def requirement_meta(self, token: str):
        return self.requirements.get(token) or self.aliases.get(token)

    def facet_meta(self, token: str):
        family, sep, value = token.partition(":")
        if not sep:
            return None
        family_spec = self.facets.get(family)
        if family_spec is None:
            return None
        item = family_spec["items"].get(value)
        if item is None:
            return None
        return family, item

    def requirement_tokens(self) -> list:
        return sorted(list(self.requirements) + list(self.aliases))

    def mandatory_facet_tokens(self) -> list:
        tokens = []
        for family in sorted(self.facets):
            spec = self.facets[family]
            if spec["mandatory"]:
                tokens.extend(f"{family}:{value}" for value in sorted(spec["items"]))
        return tokens

    def facet_tokens(self) -> list:
        return sorted(
            f"{family}:{value}" for family, spec in self.facets.items() for value in spec["items"]
        )


def sha256_file(rel: str) -> str:
    """Deterministic content hash of a repository file, or 'missing' when absent."""
    path = REPO / rel
    if not path.is_file():
        return "missing"
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def input_hashes() -> OrderedDict:
    """Pin every generator input (SRS, inventory, baseline, module sources) by SHA-256."""
    hashes: OrderedDict = OrderedDict()
    for rel in HASHED_INPUTS:
        hashes[rel] = sha256_file(rel)
    for name in MODULES:
        rel = f"testcases/sources/{name}.py"
        hashes[rel] = sha256_file(rel)
    return hashes


def load_inventory() -> Inventory:
    path = HERE / REQUIREMENTS_REL
    if not path.is_file():
        raise GenerateError(f"missing requirement inventory: testcases/{REQUIREMENTS_REL}")
    try:
        doc = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise GenerateError(f"testcases/{REQUIREMENTS_REL} is not valid JSON: {exc}") from exc
    if not isinstance(doc, dict):
        raise GenerateError(f"testcases/{REQUIREMENTS_REL} must contain a JSON object")
    inventory = Inventory(doc)
    if not inventory.requirements:
        raise GenerateError(f"testcases/{REQUIREMENTS_REL} declares no requirements")
    if not inventory.facets:
        raise GenerateError(f"testcases/{REQUIREMENTS_REL} declares no facet families")
    return inventory


def load_baseline() -> list:
    path = HERE / BASELINE_REL
    if not path.is_file():
        raise GenerateError(f"missing baseline ID snapshot: testcases/{BASELINE_REL}")
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise GenerateError(f"testcases/{BASELINE_REL} is not valid JSON: {exc}") from exc
    if not isinstance(data, list) or not all(isinstance(item, str) for item in data):
        raise GenerateError(f"testcases/{BASELINE_REL} must be a JSON array of case ID strings")
    return data


# --------------------------------------------------------------------------------------
# source modules
# --------------------------------------------------------------------------------------


def load_modules() -> dict:
    missing = [name for name in MODULES if not (SOURCES / f"{name}.py").is_file()]
    if missing:
        raise GenerateError(
            "missing case source module(s): "
            + ", ".join(f"testcases/sources/{name}.py" for name in missing)
        )
    modules: dict = {}
    for name in MODULES:
        path = SOURCES / f"{name}.py"
        spec = importlib.util.spec_from_file_location(f"tc_sources_{name}", path)
        if spec is None or spec.loader is None:
            raise GenerateError(f"cannot load testcases/sources/{name}.py")
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        try:
            spec.loader.exec_module(module)
        except Exception as exc:  # surface the source module failure as-is
            raise GenerateError(f"testcases/sources/{name}.py failed to import: {exc!r}") from exc
        modules[name] = module
    return modules


def collect_cases(modules: dict, problems: Problems) -> list:
    cases: list = []
    for name in MODULES:
        raw = getattr(modules[name], "CASES", None)
        if not isinstance(raw, list):
            problems.error(f"sources/{name}.py: CASES must be a list of case dicts")
            continue
        for position, case in enumerate(raw):
            if not isinstance(case, dict):
                problems.error(f"sources/{name}.py: CASES[{position}] is not a dict")
                continue
            record = OrderedDict(case)
            record["_module"] = name
            record["_position"] = position
            cases.append(record)
    return cases


def collect_fixtures(modules: dict, problems: Problems) -> OrderedDict:
    merged: OrderedDict = OrderedDict()
    owners: dict = {}
    for name in MODULES:
        raw = getattr(modules[name], "FIXTURES", None)
        if not isinstance(raw, dict):
            problems.error(
                f"sources/{name}.py: FIXTURES must be a dict of relative path -> JSON data"
            )
            continue
        for key, value in raw.items():
            if not isinstance(key, str) or not key:
                problems.error(f"sources/{name}.py: FIXTURES has an empty or non-string key")
                continue
            if key != key.replace("\\", "/"):
                problems.error(f"sources/{name}.py: fixture path {key!r} must use forward slashes")
                continue
            if not key.startswith("fixtures/") or key.endswith("/"):
                problems.error(f"sources/{name}.py: fixture path {key!r} must live under fixtures/")
                continue
            if ".." in key.split("/") or "*" in key:
                problems.error(
                    f"sources/{name}.py: fixture path {key!r} must not contain '..' or wildcards"
                )
                continue
            if is_protected(key):
                problems.error(f"sources/{name}.py: refusing to own protected path {key!r}")
                continue
            if key in merged:
                problems.error(
                    f"sources/{name}.py: fixture {key!r} already provided by sources/{owners[key]}.py"
                )
                continue
            if not key.endswith(".json"):
                problems.error(f"sources/{name}.py: fixture {key!r} must be a .json file")
                continue
            try:
                json.dumps(value)
            except (TypeError, ValueError) as exc:
                problems.error(f"sources/{name}.py: fixture {key!r} is not JSON-serializable: {exc}")
                continue
            merged[key] = value
            owners[key] = name
    return merged

# --------------------------------------------------------------------------------------
# validation
# --------------------------------------------------------------------------------------


def is_protected(rel: str) -> bool:
    parts = [part for part in rel.split("/") if part and part != "."]
    if not parts or ".." in parts:
        return True
    lowered = [part.lower() for part in parts]
    if any(part in PROTECTED_PARTS for part in lowered[:-1]):
        return True
    name = lowered[-1]
    if name in PROTECTED_NAMES:
        return True
    return any(name.endswith(suffix) for suffix in PROTECTED_SUFFIXES)


def case_origin(case: dict) -> str:
    module = case.get("_module", "?")
    position = case.get("_position", "?")
    cid = case.get("id")
    if isinstance(cid, str) and cid:
        return f"sources/{module}.py[{position}] id={cid}"
    return f"sources/{module}.py[{position}]"


def string_field(case: dict, key: str, where: str, problems: Problems, minimum: int = 1):
    value = case.get(key)
    if not isinstance(value, str) or len(value.strip()) < minimum:
        problems.error(f"{where}: field '{key}' must be a non-empty string")
        return None
    return value


def list_field(case: dict, key: str, where: str, problems: Problems, minimum: int = 0, item_type=str):
    value = case.get(key)
    if not isinstance(value, list):
        problems.error(f"{where}: field '{key}' must be a list")
        return None
    if any(not isinstance(item, item_type) for item in value):
        problems.error(f"{where}: field '{key}' must contain only {item_type.__name__} values")
        return None
    cleaned = [item.strip() for item in value] if item_type is str else list(value)
    if item_type is str and any(not item for item in cleaned):
        problems.error(f"{where}: field '{key}' must not contain empty strings")
        return None
    if len(cleaned) < minimum:
        problems.error(
            f"{where}: field '{key}' needs at least {minimum} entries, found {len(cleaned)}"
        )
        return None
    return cleaned


def steps_field(case: dict, where: str, problems: Problems):
    raw = case.get("steps")
    if not isinstance(raw, list):
        problems.error(f"{where}: field 'steps' must be a list of {{action, expected}} dicts")
        return None
    steps = []
    for index, step in enumerate(raw, 1):
        if not isinstance(step, dict):
            problems.error(f"{where}: steps[{index}] is not a dict")
            continue
        action = step.get("action")
        expected = step.get("expected")
        if not isinstance(action, str) or not action.strip():
            problems.error(f"{where}: steps[{index}].action must be a non-empty string")
            continue
        if not isinstance(expected, str) or not expected.strip():
            problems.error(f"{where}: steps[{index}].expected must be a non-empty string")
            continue
        extra = sorted(set(step) - {"action", "expected"})
        if extra:
            problems.warn(f"{where}: steps[{index}] has ignored extra keys {extra}")
        steps.append({"action": action.strip(), "expected": expected.strip()})
    if len(steps) < MINIMUMS["steps"]:
        problems.error(
            f"{where}: field 'steps' needs at least {MINIMUMS['steps']} named steps, found {len(steps)}"
        )
        return None
    return steps


def inputs_field(case: dict, where: str, problems: Problems):
    value = case.get("inputs")
    if not isinstance(value, dict) or not value:
        problems.error(f"{where}: field 'inputs' must be a non-empty JSON object")
        return None
    try:
        json.dumps(value)
    except (TypeError, ValueError) as exc:
        problems.error(f"{where}: field 'inputs' is not JSON-serializable: {exc}")
        return None
    return value


def privacy_warnings(case: dict, where: str, problems: Problems) -> None:
    blob = json.dumps(case, ensure_ascii=False, default=str)
    for domain in sorted({match.group(1).lower() for match in EMAIL_RE.finditer(blob)}):
        if not (domain.endswith(".invalid") or domain.endswith(".example")):
            problems.warn(f"{where}: email domain {domain!r} is not a reserved .invalid domain")
    for match in sorted({m.group(0) for m in PHONE_RE.finditer(blob)}):
        problems.warn(
            f"{where}: value {match!r} looks like a phone number; use a synthetic logical handle"
        )


def validate_case(case: dict, problems: Problems, inv: Inventory, fixture_paths: set) -> None:
    where = case_origin(case)

    known = set(REQUIRED_FIELDS) | {"pair"}
    for field in sorted(set(case) - known - {"_module", "_position"}):
        problems.warn(f"{where}: unexpected field {field!r} is not part of the case contract and is ignored")
    for field in REQUIRED_FIELDS:
        if field not in case:
            problems.error(f"{where}: missing required field '{field}'")

    cid = case.get("id")
    if not isinstance(cid, str) or not cid.strip():
        problems.error(f"{where}: field 'id' must be a non-empty string")
    elif cid != cid.strip():
        problems.error(f"{where}: id {cid!r} has leading/trailing whitespace")
    elif not CASE_ID_RE.match(cid):
        problems.error(
            f"{where}: id {cid!r} must match {CASE_ID_RE.pattern} (no spaces, slashes, ':' or '?')"
        )

    string_field(case, "title", where, problems, minimum=3)

    layer = case.get("layer")
    if layer not in LAYER_DIRS:
        problems.error(f"{where}: field 'layer' must be one of {list(LAYER_DIRS)}")
        layer = None

    suite = case.get("suite")
    if not isinstance(suite, str) or not SUITE_RE.match(suite) or ".." in suite.split("/"):
        problems.error(
            f"{where}: field 'suite' must be a path like 'unit/<name>.md' under one of "
            f"{list(LAYER_DIRS)}; '{PLATFORM_DIR}/' holds generated coverage maps, not case documents"
        )
    elif layer and suite.split("/")[0] != layer:
        problems.error(f"{where}: suite {suite!r} directory disagrees with layer {layer!r}")

    environment = case.get("environment")
    if environment not in ENVIRONMENTS:
        problems.error(f"{where}: field 'environment' must be one of {list(ENVIRONMENTS)}")
        environment = None

    if case.get("priority") not in PRIORITIES:
        problems.error(f"{where}: field 'priority' must be one of {list(PRIORITIES)}")
    if case.get("gate") not in GATES:
        problems.error(f"{where}: field 'gate' must be one of {list(GATES)}")
    if case.get("basis") not in BASES:
        problems.error(f"{where}: field 'basis' must be one of {list(BASES)}")

    string_field(case, "risk", where, problems, minimum=10)
    string_field(case, "automation", where, problems, minimum=10)

    requirements = list_field(case, "requirements", where, problems)
    if requirements is not None:
        for token in requirements:
            if not inv.requirement_meta(token):
                problems.error(
                    f"{where}: unknown requirement token {token!r}; use an exact SRS ID or a declared "
                    f"section alias ({', '.join(sorted(inv.aliases))})"
                )

    facets = list_field(case, "facets", where, problems)
    if facets is not None:
        for token in facets:
            if inv.facet_meta(token) is None:
                family = token.partition(":")[0]
                if family not in inv.facets:
                    problems.error(f"{where}: unknown facet family {family!r} in token {token!r}")
                else:
                    problems.error(f"{where}: unknown {family} facet token {token!r}")

    references = list_field(case, "references", where, problems, minimum=1)
    if references is not None:
        for reference in references:
            if reference.startswith("/") or ".." in reference.split("/"):
                problems.error(f"{where}: reference {reference!r} must be a repo-relative path")
                continue
            if "#" in reference or "::" in reference:
                problems.error(
                    f"{where}: reference {reference!r} must be a plain file path with no fabricated "
                    "line number or section anchor"
                )
                continue
            if not (REPO / reference).is_file():
                problems.error(f"{where}: reference {reference!r} does not exist in the repository")

    fixtures = list_field(case, "fixtures", where, problems)
    if fixtures is not None:
        for fixture in fixtures:
            if "*" in fixture or fixture.endswith("/"):
                problems.error(
                    f"{where}: fixture {fixture!r} must be a concrete file path without wildcards"
                )
            elif fixture not in fixture_paths:
                problems.error(
                    f"{where}: fixture {fixture!r} is not produced by any source module or by the generator"
                )

    preconditions = list_field(
        case, "preconditions", where, problems, minimum=MINIMUMS["preconditions"]
    )
    steps = steps_field(case, where, problems)
    assertions = list_field(case, "assertions", where, problems, minimum=MINIMUMS["assertions"])
    forbidden = list_field(case, "forbidden", where, problems, minimum=MINIMUMS["forbidden"])
    evidence = list_field(case, "evidence", where, problems, minimum=MINIMUMS["evidence"])
    list_field(case, "cleanup", where, problems, minimum=MINIMUMS["cleanup"])
    prerequisites = list_field(case, "prerequisites", where, problems)
    inputs_field(case, where, problems)

    if layer == "e2e" and steps is not None and len(steps) < E2E_RECOMMENDED_STEPS:
        problems.warn(
            f"{where}: e2e case has only {len(steps)} steps "
            f"(the contract expects a complete journey, >= {E2E_RECOMMENDED_STEPS})"
        )

    if environment == "live":
        if not prerequisites:
            problems.error(
                f"{where}: live case must declare prerequisites (approved ASM-001 lock, sandbox allowlist)"
            )
        elif not any("ASM-001" in item for item in prerequisites):
            problems.error(
                f"{where}: live case prerequisites must include the approved ASM-001 connector lock"
            )

    pair = case.get("pair")
    if layer == "e2e" and (not isinstance(pair, str) or not pair.strip()):
        problems.error(f"{where}: every e2e case must declare 'pair' (its offline/live counterpart)")
    if pair is not None and not isinstance(pair, str):
        problems.error(f"{where}: field 'pair' must be a case ID string when present")
    elif isinstance(pair, str) and pair and not CASE_ID_RE.match(pair):
        problems.error(f"{where}: pair {pair!r} is not a valid case ID")

    if preconditions is None or assertions is None or forbidden is None or evidence is None:
        return
    privacy_warnings(case, where, problems)


def validate_ids(cases: list, problems: Problems) -> dict:
    by_id: dict = {}
    for case in cases:
        cid = case.get("id")
        if not isinstance(cid, str) or not cid:
            continue
        if cid in by_id:
            problems.error(
                f"{case_origin(case)}: duplicate case id {cid!r} (also declared by {case_origin(by_id[cid])})"
            )
            continue
        by_id[cid] = case
    return by_id


def validate_baseline(cases: list, baseline: list, problems: Problems) -> dict:
    counts = Counter(case.get("id") for case in cases if isinstance(case.get("id"), str))
    baseline_set = set(baseline)
    if len(baseline_set) != len(baseline):
        repeated = sorted(cid for cid, count in Counter(baseline).items() if count > 1)
        problems.error(
            f"{BASELINE_REL} lists {len(baseline) - len(baseline_set)} duplicated baseline ID(s): {repeated}"
        )
    missing = sorted(cid for cid in baseline if counts.get(cid, 0) == 0)
    duplicated = sorted(
        cid for cid, count in counts.items() if count > 1 and cid in baseline_set
    )
    for cid in missing:
        problems.error(
            f"baseline case ID {cid!r} from {BASELINE_REL} is not produced by any source module"
        )
    for cid in duplicated:
        problems.error(f"baseline case ID {cid!r} is produced more than once")
    new_ids = sorted(str(cid) for cid in counts if cid not in baseline_set)
    duplicated_set = set(duplicated)
    return {
        "file": BASELINE_REL,
        "count": len(baseline),
        "preserved": len(baseline) - len(missing) - len(duplicated),
        "preserved_ids": [cid for cid in baseline if counts.get(cid, 0) == 1],
        "order": list(baseline),
        "missing": missing,
        "duplicated": duplicated,
        "duplicated_ids": sorted(duplicated_set),
        "new_case_ids": new_ids,
        "new_case_count": len(new_ids),
    }


def validate_pairs(cases: list, by_id: dict, problems: Problems) -> dict:
    e2e_cases = [case for case in cases if case.get("layer") == "e2e"]
    asymmetric = []
    relations = {}
    for case in e2e_cases:
        cid = case.get("id")
        pair = case.get("pair")
        if not isinstance(pair, str) or not pair:
            continue
        if pair == cid:
            problems.error(f"{case_origin(case)}: pair must not point at the case itself")
            continue
        partner = by_id.get(pair)
        if partner is None:
            problems.error(f"{case_origin(case)}: pair {pair!r} is not produced by any source module")
            continue
        relations[cid] = pair
        if partner.get("layer") != "e2e":
            problems.error(f"{case_origin(case)}: pair {pair!r} must also be an e2e case")
            continue
        if partner.get("environment") == case.get("environment"):
            problems.error(
                f"{case_origin(case)}: pair {pair!r} must run in the opposite environment "
                f"(both are {case.get('environment')!r})"
            )
        if partner.get("pair") != cid:
            asymmetric.append(f"{cid}->{pair}")
            problems.error(
                f"{case_origin(case)}: pair relation is not symmetric "
                f"({pair!r} declares pair={partner.get('pair')!r}, expected {cid!r})"
            )
        left = set(case.get("requirements") or [])
        right = set(partner.get("requirements") or [])
        if left != right:
            problems.error(
                f"{case_origin(case)}: pair {pair!r} must declare the same requirements; "
                f"only-here={sorted(left - right)} only-there={sorted(right - left)}"
            )
        left_facets = set(case.get("facets") or [])
        right_facets = set(partner.get("facets") or [])
        if left_facets != right_facets:
            problems.error(
                f"{case_origin(case)}: pair {pair!r} must declare the same coverage facets; "
                f"only-here={sorted(left_facets - right_facets)} "
                f"only-there={sorted(right_facets - left_facets)}"
            )
        for field in ("priority", "gate"):
            if case.get(field) != partner.get(field):
                problems.warn(
                    f"{case_origin(case)}: pair {pair!r} differs on {field} "
                    f"({case.get(field)!r} vs {partner.get(field)!r})"
                )
        live_member = case if case.get("environment") == "live" else partner
        live_prereq = live_member.get("prerequisites") or []
        if not live_prereq:
            problems.error(
                f"{case_origin(live_member)}: the live half of pair {pair!r} must state the approved "
                "sandbox prerequisites it needs (ASM-001 lock, allowlist, approved recipients)"
            )
        elif not any("ASM-001" in item for item in live_prereq):
            problems.error(
                f"{case_origin(live_member)}: the live half of pair {pair!r} must name the approved "
                "ASM-001 connector lock in its prerequisites"
            )

    for case in cases:
        if case.get("layer") != "e2e" and case.get("pair"):
            problems.warn(
                f"{case_origin(case)}: non-e2e case declares 'pair'; symmetric pairing is an e2e rule"
            )

    # Presence of 'pair' on every e2e case is enforced in validate_case; here we only count it.
    unpaired = sorted(case["id"] for case in e2e_cases if not case.get("pair"))
    return {
        "e2e_cases": len(e2e_cases),
        "paired_e2e_cases": len(e2e_cases) - len(unpaired),
        "asymmetric": asymmetric,
        "unpaired": unpaired,
        "relations": dict(sorted(relations.items())),
    }


def validate_both_environments(cases: list, inv: Inventory, problems: Problems) -> dict:
    e2e_cases = [case for case in cases if case.get("layer") == "e2e"]
    required = E2E_CRITERIA + PILOT_CRITERIA
    for token in required:
        if not inv.requirement_meta(token):
            problems.error(
                f"{REQUIREMENTS_REL} does not declare {token}; the inventory must list every system "
                "acceptance criterion and every pilot"
            )
    declared = [token for token in inv.requirements if token.startswith("TC-E2E-") or token.startswith("PILOT-")]
    tokens = sorted(set(declared) | set(required))
    matrix: dict = {}
    for token in tokens:
        offline = sorted(
            case["id"]
            for case in e2e_cases
            if case.get("environment") == "offline" and token in set(case.get("requirements") or [])
        )
        live = sorted(
            case["id"]
            for case in e2e_cases
            if case.get("environment") == "live" and token in set(case.get("requirements") or [])
        )
        matrix[token] = {"offline": offline, "live": live}
        if not offline:
            problems.error(f"{token}: no offline e2e case claims this system acceptance criterion")
        if not live:
            problems.error(f"{token}: no live e2e case claims this system acceptance criterion")
    return matrix


def build_coverage(cases: list, inv: Inventory) -> dict:
    requirement_cases: dict = {token: [] for token in inv.requirement_tokens()}
    facet_cases: dict = {token: [] for token in inv.facet_tokens()}
    for case in cases:
        cid = case.get("id")
        if not isinstance(cid, str):
            continue
        for token in sorted(set(case.get("requirements") or [])):
            if token in requirement_cases:
                requirement_cases[token].append(cid)
        for token in sorted(set(case.get("facets") or [])):
            if token in facet_cases:
                facet_cases[token].append(cid)
    requirement_gaps = sorted(token for token, ids in requirement_cases.items() if not ids)
    facet_gaps = sorted(token for token in inv.mandatory_facet_tokens() if not facet_cases.get(token))
    return {
        "requirement_cases": requirement_cases,
        "facet_cases": facet_cases,
        "requirement_gaps": requirement_gaps,
        "facet_gaps": facet_gaps,
    }

# --------------------------------------------------------------------------------------
# rendering
# --------------------------------------------------------------------------------------


def marker() -> str:
    return f"<!-- generated by {GENERATOR_REL}; do not edit by hand - edit sources/ instead -->"


def anchor(cid: str) -> str:
    return "case-" + re.sub(r"[^a-z0-9]+", "-", cid.lower()).strip("-")


def cell(text) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def bullets(items) -> str:
    return "\n".join(f"- {item}" for item in items)


def numbers(items) -> str:
    return "\n".join(f"{index}. {item}" for index, item in enumerate(items, 1))


def json_block(obj) -> str:
    return json.dumps(obj, indent=2, ensure_ascii=False)


def suite_title(suite: str) -> str:
    layer = suite.split("/")[0]
    stem = suite.split("/")[-1][: -len(".md")]
    return f"{layer.capitalize()} - {stem.replace('-', ' ')}"


def requirement_line(token: str, inv: Inventory) -> str:
    meta = inv.requirement_meta(token) or {}
    must = " (MUST)" if meta.get("must") else ""
    return f"`{token}` - {meta.get('title', '')} (SRS section {meta.get('srs_section', '?')}{must})"


def facet_line(token: str, inv: Inventory) -> str:
    parsed = inv.facet_meta(token)
    if not parsed:
        return f"`{token}`"
    family, item = parsed
    group = f", {item['group']}" if item.get("group") else ""
    requires = item.get("requires") or []
    suffix = f" (requires {', '.join(sorted(requires))})" if requires else ""
    return (
        f"`{token}` - {item.get('title', '')} "
        f"[{family}{group}, SRS section {item.get('srs_section', '?')}]{suffix}"
    )


def case_block(case: dict, inv: Inventory, up: str) -> str:
    cid = case["id"]
    pair = case.get("pair") or "-"
    parts = [
        f'<a id="{anchor(cid)}"></a>',
        "",
        f"### `{cid}` - {case['title']}",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Suite | `{case['suite']}` |",
        f"| Layer | {case['layer']} |",
        f"| Environment | {case['environment']} |",
        f"| Priority | {case['priority']} |",
        f"| Gate | {case['gate']} |",
        f"| Basis | {case['basis']} |",
        f"| Pair | {('`' + pair + '`') if pair != '-' else '-'} |",
        f"| Source module | `sources/{case['_module']}.py` |",
        f"| Design status | `{DEFAULT_STATUS}` |",
        "",
    ]

    requirement_tokens = case.get("requirements") or []
    parts.append("**Provenance**")
    parts.append("")
    if requirement_tokens:
        parts.append("\n".join(f"- {requirement_line(token, inv)}" for token in requirement_tokens))
    else:
        parts.append("- no requirement ID declared (extension probe)")
    parts.append("")

    parts.append(f"**Real-life risk.** {case['risk']}")
    parts.append("")

    facet_tokens = case.get("facets") or []
    if facet_tokens:
        parts.append("**Coverage facets**")
        parts.append("")
        parts.append("\n".join(f"- {facet_line(token, inv)}" for token in facet_tokens))
        parts.append("")

    parts.append("**Preconditions**")
    parts.append("")
    parts.append(numbers(case["preconditions"]))
    parts.append("")

    parts.append("**Inputs** (synthetic test configuration, never production policy)")
    parts.append("")
    parts.append("```json")
    parts.append(json_block(case["inputs"]))
    parts.append("```")
    parts.append("")

    parts.append("**Steps**")
    parts.append("")
    parts.append("| # | Action | Expected |")
    parts.append("|---|---|---|")
    for index, step in enumerate(case["steps"], 1):
        parts.append(f"| {index} | {cell(step['action'])} | {cell(step['expected'])} |")
    parts.append("")

    for label, key in (
        ("Assertions", "assertions"),
        ("Forbidden", "forbidden"),
        ("Evidence to collect (redacted)", "evidence"),
        ("Cleanup", "cleanup"),
    ):
        parts.append(f"**{label}**")
        parts.append("")
        parts.append(bullets(case[key]))
        parts.append("")

    parts.append(f"**Automation seam.** {case['automation']}")
    parts.append("")

    parts.append("**Prerequisites**")
    parts.append("")
    prerequisites = case.get("prerequisites") or []
    parts.append(bullets(prerequisites) if prerequisites else "- none beyond the offline toolchain")
    parts.append("")

    parts.append("**References**")
    parts.append("")
    parts.append(bullets(f"`{reference}`" for reference in case["references"]))
    parts.append("")

    fixtures = case.get("fixtures") or []
    parts.append("**Fixtures**")
    parts.append("")
    parts.append(
        bullets(f"[`{fixture}`]({up}{fixture})" for fixture in fixtures) if fixtures else "- none"
    )
    parts.append("")

    parts.append(
        "**Status.** `"
        + DEFAULT_STATUS
        + "` - descriptive acceptance specification for a future system under test; no application "
        "runtime exists in this repository, so nothing here has been executed. Machine-readable copy: "
        f"[`{up}{SCENARIO_DIR}/{cid}.json`]({up}{SCENARIO_DIR}/{cid}.json)."
    )
    parts.append("")
    return "\n".join(parts)


def render_suite(suite: str, cases: list, inv: Inventory) -> str:
    up = "../" * (len(suite.split("/")) - 1)
    layer = suite.split("/")[0]
    lines = [
        marker(),
        "",
        f"# {suite_title(suite)}",
        "",
        f"`{suite}` - layer `{layer}` - {len(cases)} case(s) - design status `{DEFAULT_STATUS}` throughout.",
        "",
        "Generated from " + ", ".join(f"`sources/{name}.py`" for name in MODULES) + ". "
        "Do not edit this file: change the source module and re-run `python testcases/_generate.py`.",
        "",
        "## Case index",
        "",
        "| Case ID | Environment | Priority | Gate | Title |",
        "|---|---|---|---|---|",
    ]
    for case in cases:
        lines.append(
            f"| [`{case['id']}`](#{anchor(case['id'])}) | {case['environment']} | {case['priority']} "
            f"| {case['gate']} | {cell(case['title'])} |"
        )
    lines.extend(["", "## Cases", ""])
    for case in cases:
        lines.append(case_block(case, inv, up))
    return "\n".join(lines).rstrip() + "\n"


def render_readme(inv: Inventory, cases: list, fixtures: dict, baseline_info: dict, coverage: dict) -> str:
    by_layer = Counter(case["layer"] for case in cases)
    by_env = Counter(case["environment"] for case in cases)
    coverage_line = ", ".join(f"{count} {layer}" for layer, count in sorted(by_layer.items()))
    return "\n".join(
        [
            marker(),
            "",
            "# Testcases - risk-based acceptance specifications",
            "",
            f"{len(cases)} cases generated from the SRS v0.1 blueprint: {by_env['offline']} offline, "
            f"{by_env['live']} live ({coverage_line}). Every entry is a written acceptance specification "
            "for a future system under test - not an executable test, not a mock echo and not a "
            "source-code inspection.",
            "",
            "## Honest status",
            "",
            f"- **There is no application runtime in this repository.** Nothing has been executed and the "
            f"default recorded status is `{DEFAULT_STATUS}`.",
            "- This generator never records `PASS`. A successful generation run proves document integrity, "
            "reference validity and coverage bookkeeping - never system behaviour.",
            "- Status vocabulary: " + ", ".join(f"`{item}`" for item in STATUS_VOCAB) + ".",
            "- `SKIP_ASM_001` when the approved connector lock is absent, `SKIP_UNIMPLEMENTED` when the "
            "runtime is missing, `BLOCKED_PREREQUISITE` when a sandbox feature or policy lock is "
            "unavailable. A missing prerequisite is never `PASS`.",
            "",
            "## What coverage does and does not mean",
            "",
            "- Coverage here means **traceability**: every case names exact requirement tokens and coverage "
            "facets, and the generator refuses to write output when a mandatory facet token, a baseline case "
            "ID or an offline/live E2E counterpart is missing.",
            "- Matching is exact-token set membership, never substring matching, so no ID can silently stand "
            "in for another.",
            "- This is **not** an exhaustive claim over the whole checklist surface. Failure and boundary "
            "probes live in the unit and integration layers; E2E is limited to critical journeys.",
            f"- Baseline preservation: {baseline_info['preserved']}/{baseline_info['count']} current case IDs "
            "are retained exactly once, with mixed-case and dotted IDs preserved verbatim. An older draft "
            "mentioned 343 IDs; that set is not recoverable or verifiable here and is therefore not claimed.",
            "",
            "## Layout",
            "",
            "```text",
            "testcases/",
            "|-- README.md              this guide (generated)",
            "|-- TRACEABILITY.md        case -> requirement/facet index (generated)",
            "|-- COVERAGE.md            requirement/facet -> cases, gaps (generated)",
            "|-- manifest.json          machine-readable counts, hashes and coverage (generated)",
            "|-- _generate.py           generator + validator (hand-written)",
            "|-- sources/               hand-written case sources",
            "|   |-- requirements.json  requirement inventory + mandatory facet tokens",
            f"|   |-- baseline-ids.json  {baseline_info['count']} current case IDs that must all survive",
            "|   |-- business.py        skills, sales and care, pilots, offline+live E2E",
            "|   |-- governance.py      authority / rules / NFR / ASM / command center / KPI / gates",
            "|   `-- platform.py        knowledge, entities, memory, API, C360, case FSM",
            "|-- platform/              knowledge+memory and entity coverage maps (generated)",
            "|-- fixtures/",
            "|   |-- README.md          fixture ownership, synthetic data, cleanup rules (generated)",
            "|   |-- offline/*.json     deterministic offline system-of-record (from source FIXTURES)",
            "|   |-- live/env.example   secret-free sandbox placeholder (generated)",
            "|   |-- live/README.md     live sandbox guide (generated)",
            "|   `-- scenarios/*.json   per-case machine-readable spec copies (generated)",
            "|-- unit/  integration/  e2e/  governance/    case documents (generated)",
            "`-- .gitignore             keeps local sandbox env and run results out of git",
            "```",
            "",
            "## Strategy",
            "",
            "```text",
            "        E2E (e2e/offline.md + e2e/live.md)   few, critical complete journeys",
            "     Integration (API, C360, FSM, command center, routing)",
            "  Unit (skills, authority, business rules, knowledge, entities)",
            "```",
            "",
            "- Many fast isolated cases carry the failure, boundary and negative load; E2E carries complete "
            "outcomes with evidence.",
            "- Every E2E case is paired offline/live with an identical requirement set, so the same observable "
            "contract is specified twice: against intercepted fixtures and against an approved sandbox.",
            "- Cases are independent: each owns its namespace (`run_id` / `case_id` / `worker`), its setup and "
            "its cleanup. Waits are condition or deadline based, never fixed sleeps.",
            "- Core policy, routing and evidence paths are never replaced by stubbed results.",
            "",
            "## Offline vs live",
            "",
            "| | Offline | Live |",
            "|---|---|---|",
            "| Data | [`fixtures/offline/`](fixtures/offline/) JSON system-of-record mocks | sandbox records created per case |",
            "| Network | all vendor HTTP intercepted | approved sandbox endpoints only, never production |",
            "| Identity | synthetic handles (`cust-a`, `SKU-OK`) | sandbox IDs mapped through gitignored `fixtures/live/env.local` |",
            "| Evidence | mock/provider call logs | provider receipts plus audit records |",
            "| Gate | none | approved ASM-001 connector lock, sandbox allowlist, approved recipients |",
            "| Waiting | fixture/mock condition | provider webhook or status condition |",
            "| Cleanup | reset namespaced mock state | retire only what the case created; keep immutable receipts |",
            "",
            "## Regenerating",
            "",
            "```bash",
            "python testcases/_generate.py            # validate, then write docs, fixtures and manifest",
            "python testcases/_generate.py --check    # validate and compare with disk; writes nothing",
            "```",
            "",
            "Python 3 standard library only, no network, no runtime: these case documents are "
            "specifications, and no runtime test was executed to produce them. Generation validates first and "
            "writes only after every check passes, each file through a temporary file plus an atomic replace, "
            "and it never rewrites `_generate.py`, `sources/*.py`, `sources/requirements.json` or "
            "`sources/baseline-ids.json`. Output is deterministic: regenerating without source changes leaves "
            "the tree byte-identical, and no timestamp or run state is embedded anywhere. `manifest.json` "
            "pins the SHA-256 of every input (SRS, inventory, baseline, source modules), and `--check` "
            "re-reads the generated files and the manifest and exits non-zero on validation errors, missing "
            "or stale output, and unexpected leftover generated files (for example an obsolete catalogue "
            "document). Errors are reported per case with the owning source module and position.",
            "",
            "## Validation performed before any write",
            "",
            "Required field types and detail minima (at least 3 named steps, 3 assertions, 2 forbidden results, "
            "2 evidence items, 1 cleanup step, 2 preconditions, non-empty synthetic `inputs`, concrete `risk` "
            "and `automation` seam); unique case IDs with all baseline IDs retained exactly once; layer/suite "
            "agreement; valid environment, priority, gate and basis; reference paths that exist in the "
            "repository; requirement and facet tokens declared in `sources/requirements.json`; fixtures that "
            "exist in the merged source `FIXTURES`; complete mandatory facet coverage; every TC-E2E and PILOT "
            "criterion in both environments; symmetric offline/live E2E pairs with identical requirement sets "
            "and live prerequisites naming the approved ASM-001 lock.",
            "",
            "Unclaimed requirement IDs are reported as coverage gaps in [`COVERAGE.md`](COVERAGE.md) and in "
            "`manifest.json`; unclaimed mandatory facet tokens are hard errors.",
            "",
            "## Secrets, results and receipts",
            "",
            "- [`fixtures/live/env.example`](fixtures/live/env.example) is a placeholder. Its presence is "
            "**not** approval: a live run still requires the approved ASM-001 lock and an allowlist.",
            "- Real sandbox values belong in `fixtures/live/env.local` or the process environment, both kept "
            "out of git by [`.gitignore`](.gitignore). The generator never reads, writes or deletes local env "
            "files.",
            "- Run results, receipts and scratch evidence stay in `results/`, which is gitignored. Sandbox "
            "receipts kept for audit are immutable: a case deletes only the records it created itself.",
            "- Never mark a live case `PASS` without provider evidence, and never delete a sent message to "
            "pretend it was not sent.",
            "",
            "## Indexes",
            "",
            f"- [`TRACEABILITY.md`](TRACEABILITY.md) - all {len(cases)} cases with suite, environment, layer, "
            "priority, gate, basis, pair and requirement tokens.",
            "- [`COVERAGE.md`](COVERAGE.md) - reverse map from every requirement and facet token to its cases, "
            "plus the remaining gaps.",
            f"- [`manifest.json`](manifest.json) - machine-readable counts, SHA-256 of every generator input "
            f"and coverage ({len(fixtures)} fixture files from source modules).",
            f"- [`{PLATFORM_KNOWLEDGE_DOC}`]({PLATFORM_KNOWLEDGE_DOC}) - knowledge base (section 10) and memory "
            "(section 16) facet map.",
            f"- [`{PLATFORM_ENTITIES_DOC}`]({PLATFORM_ENTITIES_DOC}) - canonical entity (section 14) facet map.",
            f"- [`{REQUIREMENTS_REL}`]({REQUIREMENTS_REL}) - requirement inventory "
            f"({len(inv.requirements)} requirement IDs, {len(inv.aliases)} section aliases, "
            f"{len(inv.mandatory_facet_tokens())} mandatory facet tokens).",
            f"- [`../{SRS_REL}`](../{SRS_REL}) - authoritative SRS v0.1 (AI-REV-SRS-001).",
            "",
        ]
    ).rstrip() + "\n"

def render_traceability(cases: list, inv: Inventory, baseline_info: dict, pairs: dict) -> str:
    by_id = {case["id"]: case for case in cases if isinstance(case.get("id"), str)}
    lines = [
        marker(),
        "",
        "# Traceability - case index",
        "",
        f"{len(cases)} cases, every ID taken verbatim from the source modules (mixed case and dots preserved; "
        "no ID normalisation anywhere). One row per case; the reverse direction is in "
        "[`COVERAGE.md`](COVERAGE.md). Nothing in this file is evidence of execution: there is no application "
        f"runtime in this repository and every case stays `{DEFAULT_STATUS}`.",
        "",
        "## Baseline preservation",
        "",
        f"- Current baseline: {baseline_info['count']} case IDs from "
        f"[`{BASELINE_REL}`]({BASELINE_REL}) (a snapshot taken before this generation).",
        f"- Preserved exactly once: {baseline_info['preserved']}. Missing: "
        f"{len(baseline_info['missing'])}. Duplicated: {len(baseline_info['duplicated'])}.",
        f"- New descriptive case IDs added by this generation: {len(baseline_info['new_case_ids'])}.",
        "- Every baseline ID below resolves to a case document; IDs are matched as exact strings, so "
        "`E2E-LIVE-001` is never satisfied by `E2E-LIVE-0010` and `INT-FR-CS-001-OTHERS` is never satisfied "
        "by `INT-FR-CS-001-OTHER`.",
        "- An older draft of this suite mentioned 343 IDs. That set cannot be recovered or verified from the "
        "repository, so this document claims only the current baseline snapshot; no historic ID is invented "
        "and no unavailable set is claimed as preserved.",
        "",
        "## Baseline ID placement",
        "",
        "| Baseline case ID | Suite | Layer | Environment |",
        "|---|---|---|---|",
    ]
    for cid in baseline_info.get("order") or sorted(by_id):
        case = by_id.get(cid)
        if case is None:
            lines.append(f"| `{cid}` | **MISSING - no case produces this ID** | - | - |")
            continue
        lines.append(
            f"| [`{cid}`]({case['suite']}#{anchor(cid)}) | `{case['suite']}` | {case['layer']} "
            f"| {case['environment']} |"
        )

    lines.extend(
        [
            "",
            "## Cases",
            "",
            "| Case ID | Suite | Layer | Env | Priority | Gate | Basis | Pair | Requirements | Facets |",
            "|---|---|---|---|---|---|---|---|---|---|",
        ]
    )
    for case in sorted(cases, key=lambda item: (item["suite"], item["id"])):
        requirements = case.get("requirements") or []
        facets = case.get("facets") or []
        pair = case.get("pair") or "-"
        lines.append(
            f"| [`{case['id']}`]({case['suite']}#{anchor(case['id'])}) | `{case['suite']}` "
            f"| {case['layer']} | {case['environment']} | {case['priority']} | {case['gate']} "
            f"| {case['basis']} | {('`' + pair + '`') if pair != '-' else '-'} "
            f"| {cell(', '.join(f'`{token}`' for token in requirements)) or '-'} "
            f"| {cell(', '.join(f'`{token}`' for token in facets)) or '-'} |"
        )

    lines.extend(
        [
            "",
            "## Offline/live pairing",
            "",
            f"{pairs['paired_e2e_cases']}/{pairs['e2e_cases']} e2e case(s) declare a counterpart; the partner "
            "must be an e2e case in the opposite environment, must point back, and must declare the same "
            f"requirements and facets. Unsymmetrical pair relations: {len(pairs['asymmetric'])}. "
            f"Unpaired e2e cases: {len(pairs['unpaired'])}.",
            "",
            "| E2E case | Counterpart |",
            "|---|---|",
        ]
    )
    for cid, partner in sorted((pairs.get("relations") or {}).items()):
        lines.append(f"| `{cid}` | `{partner}` |")

    lines.extend(
        [
            "",
            "## Documents",
            "",
            "| Suite | Layer | Cases |",
            "|---|---|---|",
        ]
    )
    per_suite = Counter(case["suite"] for case in cases)
    for suite in sorted(per_suite):
        lines.append(f"| [`{suite}`]({suite}) | {suite.split('/')[0]} | {per_suite[suite]} |")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_coverage(inv: Inventory, cases: list, coverage: dict, both_env: dict) -> str:
    requirement_cases = coverage["requirement_cases"]
    facet_cases = coverage["facet_cases"]
    lines = [
        marker(),
        "",
        "# Coverage - reverse map",
        "",
        "Membership below is **exact token set membership**, never substring matching: a case covers `SRS-02` "
        "only if it declares `SRS-02`, and `TC-E2E-001` is never satisfied by `TC-E2E-0010`. Coverage is a "
        "traceability statement about specifications, not evidence that anything has been executed: every case "
        f"is `{DEFAULT_STATUS}`.",
        "",
        "## Requirement reverse map",
        "",
        "| Requirement | Kind | Cases | Case IDs |",
        "|---|---|---|---|",
    ]
    for token in sorted(inv.requirements):
        meta = inv.requirements[token]
        ids = requirement_cases.get(token, [])
        listed = ", ".join(f"`{cid}`" for cid in ids) if ids else "**GAP - no case claims this requirement**"
        lines.append(f"| `{token}` | {meta.get('kind', '')} | {len(ids)} | {listed} |")
    lines.extend(["", "## Section aliases", "", "| Alias | Cases | Case IDs |", "|---|---|---|"])
    for token in sorted(inv.aliases):
        ids = requirement_cases.get(token, [])
        listed = ", ".join(f"`{cid}`" for cid in ids) if ids else "**GAP - no case claims this section obligation**"
        lines.append(f"| `{token}` | {len(ids)} | {listed} |")

    lines.extend(["", "## Facet coverage", ""])
    for family in sorted(inv.facets):
        spec = inv.facets[family]
        tokens = sorted(spec["items"])
        covered = sum(1 for token in tokens if facet_cases.get(f"{family}:{token}"))
        lines.append(f"### {family} - {covered}/{len(tokens)} covered")
        lines.append("")
        lines.append(f"{spec['description']} (SRS section {spec['srs_section']}.)")
        lines.append("")
        lines.append("| Token | Requires | Cases | Case IDs |")
        lines.append("|---|---|---|---|")
        for token in tokens:
            full = f"{family}:{token}"
            item = spec["items"][token]
            ids = facet_cases.get(full, [])
            listed = ", ".join(f"`{cid}`" for cid in ids) if ids else "**GAP**"
            requires = ", ".join(f"`{req}`" for req in (item.get("requires") or [])) or "-"
            lines.append(f"| `{token}` | {requires} | {len(ids)} | {listed} |")
        lines.append("")

    lines.extend(
        [
            "## Both environments (system acceptance criteria and pilots)",
            "",
            "| Criterion | Offline e2e cases | Live e2e cases |",
            "|---|---|---|",
        ]
    )
    for token in sorted(both_env):
        entry = both_env[token]
        offline = ", ".join(f"`{cid}`" for cid in entry["offline"]) or "**GAP**"
        live = ", ".join(f"`{cid}`" for cid in entry["live"]) or "**GAP**"
        lines.append(f"| `{token}` | {offline} | {live} |")

    lines.extend(["", "## Remaining gaps", ""])
    if coverage["facet_gaps"]:
        lines.append("Mandatory facet tokens with no case (these are hard errors and must be empty):")
        lines.append("")
        lines.extend(f"- `{token}`" for token in coverage["facet_gaps"])
    else:
        lines.append("- No mandatory facet token is uncovered.")
    lines.append("")
    if coverage["requirement_gaps"]:
        lines.append(
            "Requirement or alias tokens with no case (reported, not fatal: a token may be carried by a "
            "section-level obligation or be planned for a later gate):"
        )
        lines.append("")
        lines.extend(f"- `{token}`" for token in coverage["requirement_gaps"])
    else:
        lines.append("- Every requirement ID and section alias is claimed by at least one case.")
    lines.extend(
        [
            "",
            "## Design status",
            "",
            f"- Total cases: {len(cases)}. Every case is `{DEFAULT_STATUS}`: the specifications exist, the "
            "system under test does not.",
            "- Gaps above are documented rather than hidden. They are not evidence of coverage and not a claim "
            "that the checklist surface is exhaustively covered.",
            "",
            "## Related maps",
            "",
            f"- [`{PLATFORM_KNOWLEDGE_DOC}`]({PLATFORM_KNOWLEDGE_DOC}) - knowledge base (section 10) and AI "
            "memory (section 16) tokens with their covering cases.",
            f"- [`{PLATFORM_ENTITIES_DOC}`]({PLATFORM_ENTITIES_DOC}) - canonical entity (section 14) tokens "
            "with their covering cases.",
            "- [`TRACEABILITY.md`](TRACEABILITY.md) - the forward direction: every case with its suite, "
            "environment, pair and tokens.",
            "- [`manifest.json`](manifest.json) - the same counts, the coverage gaps and the SHA-256 of every "
            "generator input in machine-readable form.",
            "",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def render_platform_facets(inv: Inventory, cases: list, coverage: dict, title: str, blurb: str, families) -> str:
    """Derived coverage map for one group of facet families (never a case document)."""
    facet_cases = coverage["facet_cases"]
    lines = [
        marker(),
        "",
        f"# {title}",
        "",
        blurb,
        "",
        "This is a **derived coverage map**, not a case document and not evidence of execution: it is "
        "rendered from the coverage facets the cases declare in `sources/{business,governance,platform}.py` "
        f"against `{REQUIREMENTS_REL}`. No case declares a suite under `{PLATFORM_DIR}/`. Every entry is "
        f"`{DEFAULT_STATUS}` - the specifications exist, the system under test does not.",
        "",
    ]
    for family in families:
        spec = inv.facets.get(family)
        if spec is None:
            continue
        tokens = sorted(spec["items"])
        covered = sum(1 for token in tokens if facet_cases.get(f"{family}:{token}"))
        lines.append(f"## {family} - {covered}/{len(tokens)} covered")
        lines.append("")
        lines.append(f"{spec['description']} (SRS section {spec['srs_section']}.)")
        lines.append("")
        lines.append("| Token | Title | Group | Requires | Cases | Case IDs |")
        lines.append("|---|---|---|---|---|---|")
        for token in tokens:
            full = f"{family}:{token}"
            item = spec["items"][token]
            ids = facet_cases.get(full, [])
            listed = ", ".join(f"`{cid}`" for cid in ids) if ids else "**GAP - no case declares this facet**"
            requires = ", ".join(f"`{req}`" for req in (item.get("requires") or [])) or "-"
            lines.append(
                f"| `{token}` | {cell(item.get('title', ''))} | {cell(item.get('group', ''))} | "
                f"{requires} | {len(ids)} | {listed} |"
            )
        lines.append("")
        gaps = [token for token in tokens if not facet_cases.get(f"{family}:{token}")]
        if gaps:
            lines.append("Uncovered tokens in this family (a mandatory facet gap is a hard generator error):")
            lines.append("")
            lines.extend(f"- `{family}:{token}`" for token in gaps)
        else:
            lines.append("No uncovered token in this family.")
        lines.append("")
    lines.extend(
        [
            "## Reading this map",
            "",
            "- Coverage means traceability: an exact-token set membership between a facet token and the "
            "cases that declare it, never substring matching.",
            "- A token being covered means the checklist surface is *specified somewhere*; it is not a claim "
            "that the behaviour has been observed, and this suite records no `PASS` for a system that has "
            "no runtime in this repository.",
            f"- The full reverse map for every requirement and facet family is in [`../COVERAGE.md`](../COVERAGE.md); "
            f"per-case detail is in the case documents under `unit/`, `integration/`, `e2e/` and `governance/`.",
            "",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def render_platform_knowledge_memory(inv: Inventory, cases: list, coverage: dict) -> str:
    return render_platform_facets(
        inv,
        cases,
        coverage,
        "Platform - knowledge base and memory coverage",
        "Which cases exercise the required knowledge base paths (SRS section 10) and which exercise each "
        "AI memory store (section 16). Knowledge coverage is only meaningful when a case reads the real "
        "corpus entry with its version and provenance and answers from it, so a knowledge path claimed by "
        "a case that never queries it is not coverage.",
        ("kb", "memory"),
    )


def render_platform_entities(inv: Inventory, cases: list, coverage: dict) -> str:
    return render_platform_facets(
        inv,
        cases,
        coverage,
        "Platform - canonical entity coverage",
        "Which cases exercise each of the canonical entities of the core data model (SRS section 14). "
        "Entity coverage means consumer-contract behaviour - create/read/update invariants, tenancy and "
        "identity isolation, retention - not the mere presence of a table or column definition.",
        ("entity",),
    )


def arrange(counter: Counter, keys=None) -> dict:
    if keys is None:
        keys = sorted(counter)
    return {key: counter[key] for key in keys if counter[key]}


def render_manifest(
    inv, cases, fixtures, fixture_owners_map, baseline_info, coverage, pairs, both_env, problems, documents
) -> str:
    requirement_cases = coverage["requirement_cases"]
    facet_cases = coverage["facet_cases"]
    manifest = OrderedDict(
        [
            ("schema", "testcases.manifest/1"),
            ("generator", GENERATOR_REL),
            ("srs_source", SRS_REL),
            ("requirements_source", REQUIREMENTS_REL),
            ("baseline_source", BASELINE_REL),
            ("case_source_modules", [f"sources/{name}.py" for name in MODULES]),
            (
                "input_hashes",
                OrderedDict(
                    [
                        ("algorithm", "sha256"),
                        (
                            "note",
                            "SHA-256 of every generator input at the time these documents were produced; "
                            "--check re-reads them so a review can pin exactly which sources were rendered.",
                        ),
                        ("files", input_hashes()),
                    ]
                ),
            ),
            (
                "design_status",
                OrderedDict(
                    [
                        ("default", DEFAULT_STATUS),
                        ("vocabulary", STATUS_VOCAB),
                        ("runtime_available", False),
                        ("pass_recorded", False),
                        ("source_documents_are_specifications", True),
                        (
                            "note",
                            "No application runtime exists and no runtime test was executed. The case "
                            "documents are specifications. Generation proves document integrity and "
                            "traceability only; the generator never records PASS.",
                        ),
                    ]
                ),
            ),
            (
                "counts",
                OrderedDict(
                    [
                        ("cases", len(cases)),
                        ("by_layer", arrange(Counter(case["layer"] for case in cases), list(LAYER_DIRS))),
                        ("by_environment", arrange(Counter(case["environment"] for case in cases), list(ENVIRONMENTS))),
                        ("by_priority", arrange(Counter(case["priority"] for case in cases), list(PRIORITIES))),
                        ("by_gate", arrange(Counter(case["gate"] for case in cases), list(GATES))),
                        ("by_basis", arrange(Counter(case["basis"] for case in cases), list(BASES))),
                        ("by_suite", arrange(Counter(case["suite"] for case in cases))),
                        ("by_source_module", arrange(Counter(case["_module"] for case in cases), list(MODULES))),
                    ]
                ),
            ),
            ("baseline", baseline_info),
            (
                "coverage",
                OrderedDict(
                    [
                        (
                            "requirements",
                            OrderedDict(
                                [
                                    ("total", len(requirement_cases)),
                                    ("covered", sum(1 for ids in requirement_cases.values() if ids)),
                                    ("gaps", coverage["requirement_gaps"]),
                                    ("cases_per_token", {t: requirement_cases[t] for t in sorted(requirement_cases)}),
                                ]
                            ),
                        ),
                        (
                            "facets",
                            OrderedDict(
                                [
                                    ("total", len(facet_cases)),
                                    ("covered", sum(1 for ids in facet_cases.values() if ids)),
                                    ("gaps", coverage["facet_gaps"]),
                                    ("cases_per_token", {t: facet_cases[t] for t in sorted(facet_cases)}),
                                ]
                            ),
                        ),
                        ("both_environments", both_env),
                    ]
                ),
            ),
            ("pairs", pairs),
            ("documents", documents),
            ("derived_documents", list(DERIVED_DOCS)),
            (
                "fixtures",
                OrderedDict(
                    [
                        ("source_fixtures", dict(sorted(fixture_owners_map.items()))),
                        ("fixture_count", len(fixtures)),
                        ("generator_fixtures", [LIVE_ENV_EXAMPLE, FIXTURES_GUIDE, LIVE_FIXTURES_GUIDE]),
                        ("scenario_exports", len(cases)),
                    ]
                ),
            ),
            (
                "validation",
                OrderedDict(
                    [
                        ("errors", problems.errors),
                        ("warnings", problems.warnings),
                        ("clean", problems.ok),
                    ]
                ),
            ),
        ]
    )
    return json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"


def render_fixtures_guide(fixture_owners_map: dict) -> str:
    lines = [
        marker(),
        "",
        "# Fixtures",
        "",
        "All fixture data is synthetic test configuration. It is not production data, not an approved policy "
        "and not a KPI baseline (ASM-002..ASM-005 stay unconfirmed until their owners lock them).",
        "",
        "## Offline fixtures",
        "",
        "| Fixture | Owner |",
        "|---|---|",
    ]
    for path, owner in sorted(fixture_owners_map.items()):
        lines.append(f"| `{path}` | `{owner}` |")
    lines.extend(
        [
            "",
            "Rules applied to every offline fixture:",
            "",
            "- Frozen clock `2026-01-15T10:00:00Z`; no fixture reads the wall clock.",
            "- Reserved `.invalid` domains and synthetic logical handles instead of real phone numbers, tokens "
            "or customer data.",
            "- Consent is scoped per channel and purpose; never a wildcard positive. A customer-supplied "
            "`verification_status` payload is not trusted as identity - identity resolves from the "
            "gateway-bound session or the verified identity registry.",
            "- Tenant IDs are fixed example UUIDs; parallel runs are separated by `run_id` / `case_id` / "
            "`worker` namespaces, not by editing fixtures.",
            "- Fixture state is reset by the case that dirtied it; mock ephemeral state is cleared in cleanup.",
            "",
            "## Live fixtures",
            "",
            f"- [`fixtures/live/env.example`]({LIVE_ENV_EXAMPLE.split('/')[-1]}) is a secret-free placeholder and "
            "a checklist, not an approval. Live execution still requires the approved ASM-001 connector lock, "
            "an allowlisted sandbox and approved recipients.",
            "- Real values live in `fixtures/live/env.local` or the process environment. That file is gitignored, "
            "and the generator never creates, reads or overwrites it.",
            f"- See [`fixtures/live/README.md`](live/README.md) for the sandbox workflow.",
            "",
            "## Case exports",
            "",
            "- `fixtures/scenarios/<case id>.json` mirrors one case in machine-readable form (same fields as "
            "the case document: requirements, facets, inputs, steps, assertions, forbidden, evidence, cleanup, "
            "automation, prerequisites, references, fixtures) with `status: NOT_RUN`. It is a specification "
            "export, not a test artifact from a run.",
            "",
            "## Generated, never hand-edited",
            "",
            "Everything in this directory is produced by `python testcases/_generate.py` from the `FIXTURES` "
            "dict of the source modules and the case records, except `env.local` (yours, untracked) and "
            "`results/` (local run artifacts). `--check` reports any file here that the generator does not "
            "produce, and the generator never deletes a file it did not produce.",
            "",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def render_live_guide() -> str:
    return "\n".join(
        [
            marker(),
            "",
            "# Live sandbox fixtures",
            "",
            "Staged sandbox endpoints only - never production. Copy `env.example` to `env.local`, fill it with "
            "sandbox values, and keep it out of git (it is already in `.gitignore`, and the generator will "
            "never write it).",
            "",
            "## Before any live case runs",
            "",
            "1. The ASM-001 connector lock is approved and its path is set in `LIVE_CONNECTORS_LOCK`.",
            "2. The sandbox hosts are on the approved allowlist and the recipients are approved sandbox "
            "identities.",
            "3. Credentials come from the environment, never from a tracked file.",
            "4. Logical fixture handles (`cust-a`, `SKU-OK`) are mapped to sandbox IDs through `env.local`.",
            "",
            "If the lock is missing every live case is `SKIP_ASM_001`; an unsupported sandbox feature or an "
            "unlocked policy is `BLOCKED_PREREQUISITE`. Neither is `PASS`, and neither may be reported as one.",
            "",
            "## Identity and data",
            "",
            "- Each case creates its own sandbox records with a unique `run_id` and never shares a session "
            "with another case.",
            "- Consent is checked per channel and purpose before any outbound message; a denied action needs no "
            "provider receipt - the zero-call audit record plus the provider test sink is the oracle.",
            "",
            "## Cleanup, receipts and immutability",
            "",
            "- Cleanup retires only what the case created, through the supported sandbox APIs.",
            "- Audit records and provider receipts are immutable: never delete a message that was actually sent "
            "to pretend it was not, and never remove pre-existing sandbox records.",
            "- Artifacts that cannot be deleted are reported instead of hidden.",
            "- Local run results, receipts and scratch evidence go to `results/`, which is gitignored.",
            "",
        ]
    ).rstrip() + "\n"


def render_env_example() -> str:
    return "\n".join(
        [
            "# Live sandbox placeholders for testcases/live/*.example - NOT a credential file and NOT an",
            "# approval. Copy to env.local (gitignored) and fill with approved sandbox values.",
            "#",
            "# Required before any live case: an approved ASM-001 connector lock. Without it, live cases are",
            "# SKIP_ASM_001. Nothing here is validated by the generator: the file existing proves nothing.",
            "",
            "# ASM-001 approved connector lock (path to the owner-approved lock document)",
            "LIVE_CONNECTORS_LOCK=",
            "",
            "# Sandbox endpoints and tenant",
            "LIVE_BASE_URL=https://sandbox.api.invalid",
            "LIVE_ERP_BASE_URL=https://sandbox.erp.invalid",
            "LIVE_TENANT_ID=",
            "LIVE_ALLOWLIST_HOSTS=sandbox.api.invalid,sandbox.erp.invalid",
            "",
            "# Credentials are read from the process environment, never from this file",
            "# LIVE_ERP_TOKEN=  (set in the shell, do not store here)",
            "",
            "# Approved sandbox identities (logical fixture handle -> sandbox id)",
            "LIVE_CUSTOMER_A_SANDBOX_ID=",
            "LIVE_CUSTOMER_B_SANDBOX_ID=",
            "LIVE_CUSTOMER_A_CONTACT=sandbox-a@example.invalid",
            "LIVE_CUSTOMER_B_CONTACT=sandbox-b@example.invalid",
            "LIVE_SKU_OK=",
            "LIVE_SKU_ZERO=",
            "LIVE_ORDER_A=",
            "LIVE_ORDER_B=",
            "",
            "# Channel used by live journeys (API-003 connector names)",
            "LIVE_CHAT_CHANNEL=WEB_APP_CHAT",
            "",
            "# Local results/receipts directory; gitignored, never committed",
            "LIVE_RESULTS_DIR=results/",
            "",
            "# Every live case creates its own records under a unique run id and deletes only those in cleanup.",
            "",
        ]
    )


def scenario_record(case: dict) -> OrderedDict:
    return OrderedDict(
        [
            ("id", case["id"]),
            ("title", case["title"]),
            ("document", case["suite"]),
            ("layer", case["layer"]),
            ("environment", case["environment"]),
            ("priority", case["priority"]),
            ("gate", case["gate"]),
            ("basis", case["basis"]),
            ("pair", case.get("pair")),
            ("status", DEFAULT_STATUS),
            ("source_module", f"sources/{case['_module']}.py"),
            ("requirements", case["requirements"]),
            ("facets", case["facets"]),
            ("risk", case["risk"]),
            ("preconditions", case["preconditions"]),
            ("inputs", case["inputs"]),
            ("steps", case["steps"]),
            ("assertions", case["assertions"]),
            ("forbidden", case["forbidden"]),
            ("evidence", case["evidence"]),
            ("cleanup", case["cleanup"]),
            ("automation", case["automation"]),
            ("prerequisites", case["prerequisites"]),
            ("references", case["references"]),
            ("fixtures", case["fixtures"]),
            ("srs_source", SRS_REL),
            ("generator", GENERATOR_REL),
            (
                "note",
                "Generated acceptance specification. Plain specification, not an executable test; "
                "no application runtime exists, so the status is NOT_RUN.",
            ),
        ]
    )


def build_outputs(cases, fixtures, inv, baseline_info, coverage, pairs, both_env, problems, fixture_owners_map):
    outputs: OrderedDict = OrderedDict()

    suites: dict = {}
    for case in sorted(cases, key=lambda item: (item["suite"], item["id"])):
        suites.setdefault(case["suite"], []).append(case)

    documents = []
    for suite in sorted(suites):
        outputs[suite] = render_suite(suite, suites[suite], inv)
        documents.append({"path": suite, "cases": len(suites[suite]), "layer": suite.split("/")[0]})

    outputs["README.md"] = render_readme(inv, cases, fixtures, baseline_info, coverage)
    outputs["TRACEABILITY.md"] = render_traceability(cases, inv, baseline_info, pairs)
    outputs["COVERAGE.md"] = render_coverage(inv, cases, coverage, both_env)
    outputs[PLATFORM_KNOWLEDGE_DOC] = render_platform_knowledge_memory(inv, cases, coverage)
    outputs[PLATFORM_ENTITIES_DOC] = render_platform_entities(inv, cases, coverage)

    for path, data in sorted(fixtures.items()):
        outputs[path] = json.dumps(data, indent=2, ensure_ascii=False) + "\n"

    outputs[FIXTURES_GUIDE] = render_fixtures_guide(fixture_owners_map)
    outputs[LIVE_FIXTURES_GUIDE] = render_live_guide()
    outputs[LIVE_ENV_EXAMPLE] = render_env_example()

    for case in sorted(cases, key=lambda item: item["id"]):
        outputs[f"{SCENARIO_DIR}/{case['id']}.json"] = json.dumps(
            scenario_record(case), indent=2, ensure_ascii=False
        ) + "\n"

    outputs["manifest.json"] = render_manifest(
        inv,
        cases,
        fixtures,
        fixture_owners_map,
        baseline_info,
        coverage,
        pairs,
        both_env,
        problems,
        documents,
    )
    assert_output_paths(outputs)
    return outputs


def assert_output_paths(outputs: dict) -> None:
    """Refuse any output that would leave testcases/ or overwrite a hand-written input."""
    for rel in outputs:
        if rel.startswith("/") or ".." in rel.split("/") or rel.endswith("/"):
            raise GenerateError(f"generated path escapes testcases/: {rel!r}")
        if rel.replace("\\", "/") in SOURCE_OWNED:
            raise GenerateError(
                f"generated path {rel!r} collides with a hand-written input; the generator never "
                "rewrites its own sources"
            )
        if is_protected(rel):
            raise GenerateError(f"generated path {rel!r} is protected (local env, results or secrets)")


def stale_extras(outputs: dict) -> list:
    """Generated-looking files on disk that this run does not produce (never deleted by us)."""
    stale = []
    for directory, pattern in (
        ("fixtures/offline", "*.json"),
        (SCENARIO_DIR, "*.json"),
        ("fixtures/live", "*.json"),
        (PLATFORM_DIR, "*.md"),
        (".", "*.md"),
        (".", "*.tmp"),
    ):
        base = HERE / directory
        if not base.is_dir():
            continue
        for path in sorted(base.glob(pattern)):
            if not path.is_file():
                continue
            rel = path.relative_to(HERE).as_posix()
            if rel in outputs:
                continue
            if is_protected(rel):
                continue
            stale.append(rel)
    for layer in LAYER_DIRS:
        base = HERE / layer
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*.md")):
            rel = path.relative_to(HERE).as_posix()
            if rel not in outputs:
                stale.append(rel)
    return stale


def check_outputs(outputs: dict) -> int:
    """Compare generated content (case docs, fixtures, manifest, derived maps) with disk."""
    drift = []
    matched = 0
    for rel in sorted(outputs):
        path = HERE / rel
        if not path.is_file():
            drift.append(f"missing generated output: testcases/{rel}")
        elif path.read_text(encoding="utf-8") != outputs[rel]:
            drift.append(f"stale generated output (content differs from sources): testcases/{rel}")
        else:
            matched += 1
    for rel in stale_extras(outputs):
        drift.append(f"unexpected generated file that this generator does not produce: testcases/{rel}")
    if drift:
        for item in drift:
            print(f"STALE: {item}")
        print(
            f"FAILED: {len(drift)} generated file(s) out of date or unexpected "
            f"({matched} matched); run python testcases/_generate.py"
        )
        return 3
    print(
        f"OK: {len(outputs)} generated file(s) match the sources byte for byte, "
        f"including manifest.json and its input hashes"
    )
    return 0


def write_outputs(outputs: dict) -> list:
    """Atomically replace each generated file. All validation has already passed."""
    written = []
    for rel in sorted(outputs):
        if is_protected(rel):
            raise GenerateError(f"refusing to write protected path: testcases/{rel}")
        path = HERE / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_name(path.name + ".tmp")
        try:
            with open(temporary, "w", encoding="utf-8", newline="\n") as handle:
                handle.write(outputs[rel])
            os.replace(temporary, path)
        except OSError as exc:
            if temporary.exists():
                temporary.unlink()
            raise GenerateError(f"cannot write testcases/{rel}: {exc}") from exc
        written.append(rel)
    return written


def fixture_owners(modules: dict) -> dict:
    owners: dict = {}
    for name in MODULES:
        raw = getattr(modules[name], "FIXTURES", None)
        if isinstance(raw, dict):
            for key in raw:
                owners.setdefault(str(key), f"sources/{name}.py")
    return OrderedDict(sorted(owners.items()))


def report(problems: Problems) -> None:
    for warning in problems.warnings:
        print(f"WARN: {warning}")
    for error in problems.errors:
        print(f"ERROR: {error}")
    print(f"validation: {len(problems.errors)} error(s), {len(problems.warnings)} warning(s)")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        prog="python testcases/_generate.py",
        description="Validate the testcase sources and generate the testcases documents, fixtures and manifest.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate and compare generated output with disk; write nothing",
    )
    args = parser.parse_args(argv)

    problems = Problems()
    try:
        inv = load_inventory()
        baseline = load_baseline()
        modules = load_modules()
    except GenerateError as exc:
        print(f"ERROR: {exc}")
        return 2

    cases = collect_cases(modules, problems)
    fixtures = collect_fixtures(modules, problems)

    fixture_paths = set(fixtures) | {LIVE_ENV_EXAMPLE, FIXTURES_GUIDE, LIVE_FIXTURES_GUIDE}
    for case in cases:
        validate_case(case, problems, inv, fixture_paths)

    by_id = validate_ids(cases, problems)
    baseline_info = validate_baseline(cases, baseline, problems)
    pairs = validate_pairs(cases, by_id, problems)
    both_env = validate_both_environments(cases, inv, problems)
    coverage = build_coverage(cases, inv)

    for token in coverage["facet_gaps"]:
        problems.error(f"mandatory facet token {token!r} is not covered by any case")
    for token in coverage["requirement_gaps"]:
        problems.warn(f"requirement token {token!r} is not claimed by any case (reported as a coverage gap)")

    report(problems)
    if not problems.ok:
        print(
            f"FAILED: {len(problems.errors)} validation error(s); nothing was written and no generated "
            "file was touched"
        )
        return 2

    summary = [
        f"cases: {len(cases)} from {len(modules)} source module(s) "
        f"({', '.join(f'sources/{name}.py' for name in MODULES)})",
        "layers: " + ", ".join(f"{layer} {sum(1 for c in cases if c['layer'] == layer)}" for layer in LAYER_DIRS),
        "environments: " + ", ".join(
            f"{env} {sum(1 for c in cases if c['environment'] == env)}" for env in ENVIRONMENTS
        ),
        f"baseline: {baseline_info['preserved']}/{baseline_info['count']} current IDs preserved exactly once"
        f" (+{baseline_info['new_case_count']} new descriptive IDs)",
        f"e2e pairs: {pairs['paired_e2e_cases']}/{pairs['e2e_cases']} paired offline/live",
        f"coverage: requirements {sum(1 for ids in coverage['requirement_cases'].values() if ids)}"
        f"/{len(coverage['requirement_cases'])}, facets "
        f"{sum(1 for ids in coverage['facet_cases'].values() if ids)}/{len(coverage['facet_cases'])}",
    ]

    outputs = build_outputs(
        cases,
        fixtures,
        inv,
        baseline_info,
        coverage,
        pairs,
        both_env,
        problems,
        fixture_owners(modules),
    )

    if args.check:
        status = check_outputs(outputs)
        for line in summary:
            print(line)
        print("--check wrote nothing and mutated nothing")
        return status

    try:
        written = write_outputs(outputs)
    except GenerateError as exc:
        print(f"ERROR: {exc}")
        return 2

    for line in summary:
        print(line)
    print(f"wrote {len(written)} file(s) under testcases/; every case stays {DEFAULT_STATUS}")

    leftovers = stale_extras(outputs)
    if leftovers:
        print(
            f"NOTE: {len(leftovers)} generated-looking file(s) on disk are not produced by this run and "
            "were left untouched (delete or regenerate them deliberately):"
        )
        for rel in leftovers:
            print(f"  testcases/{rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
