module.exports = {
  theme: {
    extend: {
      colors: {
        canvas: 'rgb(var(--ui-canvas) / <alpha-value>)',
        surface: 'rgb(var(--ui-surface) / <alpha-value>)',
        'surface-subtle': 'var(--color-surface-subtle)',
        'surface-raised': 'var(--color-surface-raised)',
        ink: 'rgb(var(--ui-ink) / <alpha-value>)',
        'ink-body': 'var(--color-text-body)',
        muted: 'rgb(var(--ui-muted) / <alpha-value>)',
        line: 'rgb(var(--ui-line) / <alpha-value>)',
        'line-strong': 'rgb(var(--ui-line-strong) / <alpha-value>)',
        primary: 'rgb(var(--ui-primary) / <alpha-value>)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-ink': 'rgb(var(--ui-primary-ink) / <alpha-value>)',
        interactive: 'rgb(var(--ui-focus) / <alpha-value>)',
        'interactive-hover': 'var(--color-interactive-hover)',
        'interactive-secondary': 'var(--color-interactive-secondary)',
        success: 'rgb(var(--ui-success) / <alpha-value>)',
        'success-bg': 'var(--color-success-bg)',
        'success-border': 'var(--color-success-border)',
        warning: 'rgb(var(--ui-warning) / <alpha-value>)',
        'warning-bg': 'var(--color-warning-bg)',
        'warning-border': 'var(--color-warning-border)',
        danger: 'rgb(var(--ui-danger) / <alpha-value>)',
        'danger-bg': 'var(--color-danger-bg)',
        'danger-border': 'var(--color-danger-border)',
        info: 'rgb(var(--ui-info) / <alpha-value>)',
        'info-bg': 'var(--color-info-bg)',
        'info-border': 'var(--color-info-border)',
        ai: 'rgb(var(--ui-ai) / <alpha-value>)',
        'ai-bg': 'var(--color-ai-bg)',
        'ai-border': 'var(--color-ai-border)',
        'ai-text': 'var(--color-ai-text)',
        neutral: 'var(--color-neutral)',
        'neutral-bg': 'var(--color-neutral-bg)',
        'neutral-border': 'var(--color-neutral-border)',
        demo: 'rgb(var(--ui-demo) / <alpha-value>)',
        /* Stitch aliases used by the reference screens. */
        'surface-card': 'var(--color-surface)',
        'border-subtle': 'var(--color-border-subtle)',
        'border-strong': 'var(--color-border-strong)',
        'text-display': 'var(--color-text)',
        'text-body': 'var(--color-text-body)',
        'text-muted': 'var(--color-text-muted)',
        'accent-success': 'var(--color-success)',
        'accent-warning': 'var(--color-warning)',
        'accent-danger': 'var(--color-danger)',
      },
      borderRadius: {
        xs: 'var(--radius-sm)',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-control)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        badge: 'var(--radius-badge)',
      },
      boxShadow: {
        sm: 'var(--elevation-l1)',
        md: 'var(--elevation-l2)',
        l1: 'var(--elevation-l1)',
        l2: 'var(--elevation-l2)',
        l3: 'var(--elevation-l3)',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
        id: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['var(--text-headline-xl)', { lineHeight: 'var(--line-headline-xl)', fontWeight: '600', letterSpacing: '-0.025em' }],
        'headline-lg': ['var(--text-headline-lg)', { lineHeight: 'var(--line-headline-lg)', fontWeight: '600', letterSpacing: '-0.02em' }],
        'headline-md': ['var(--text-headline-md)', { lineHeight: 'var(--line-headline-md)', fontWeight: '600', letterSpacing: '-0.015em' }],
        'headline-sm': ['var(--text-headline-sm)', { lineHeight: 'var(--line-headline-sm)', fontWeight: '600', letterSpacing: '-0.01em' }],
        'body-lg': ['var(--text-body-lg)', { lineHeight: 'var(--line-body-lg)' }],
        'body-md': ['var(--text-body-md)', { lineHeight: 'var(--line-body-md)' }],
        'body-sm': ['var(--text-body-sm)', { lineHeight: 'var(--line-body-sm)' }],
        'label-lg': ['var(--text-label-lg)', { lineHeight: 'var(--line-label-lg)', fontWeight: '500' }],
        'label-md': ['var(--text-label-md)', { lineHeight: 'var(--line-label-md)', fontWeight: '500' }],
        'label-sm': ['var(--text-label-sm)', { lineHeight: 'var(--line-label-sm)', fontWeight: '500' }],
        'code-md': ['var(--text-code-md)', { lineHeight: '1rem', fontFamily: 'var(--font-mono)' }],
        'code-sm': ['var(--text-code-sm)', { lineHeight: '0.875rem', fontFamily: 'var(--font-mono)', fontWeight: '500', letterSpacing: '0.025em' }],
      },
      spacing: {
        xs: 'var(--space-xs)',
        sm: 'var(--space-sm)',
        md: 'var(--space-md)',
        lg: 'var(--space-lg)',
        xl: 'var(--space-xl)',
        '2xl': 'var(--space-2xl)',
        gutter: 'var(--gutter)',
        sidebar: 'var(--ag-sidebar-width)',
        topbar: 'var(--ag-topbar-height)',
        'space-xs': 'var(--space-sm)',
        'space-sm': 'var(--space-md)',
        'space-md': 'var(--space-xl)',
        'space-lg': 'var(--space-2xl)',
        'space-xl': '32px',
        margin: '16px',
        'margin-desktop': '40px',
        'gutter-desktop': '28px',
      },
    },
  },
  plugins: [
    function ({ addBase }) {
      addBase({
        body: {
          fontFamily: 'var(--font-ui)',
          fontSize: '13px',
          fontVariantNumeric: 'tabular-nums',
        },
      });
    },
  ],
};
