"""Rendering helpers for generated testcase documents and scenarios."""

from __future__ import annotations

import json
from collections import Counter, OrderedDict

from .model import *
from .inputs import input_hashes
def marker() -> str:
    return f"<!-- generated by {GENERATOR_REL}; do not edit by hand - edit sources/ instead -->"


def anchor(cid: str) -> str:
    return "case-" + re.sub(r"[^a-z0-9]+", "-", cid.lower()).strip("-")


def cell(text) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def bullets(items) -> str:
    return "\n".join(f"- {item}" for item in items)


def numbers(items) -> str:
    return "\n".join(f"{index}. {item}" for index, item in enumerate(items, 1))


def json_block(obj) -> str:
    return json.dumps(obj, indent=2, ensure_ascii=False)


def suite_title(suite: str) -> str:
    layer = suite.split("/")[0]
    stem = suite.split("/")[-1][: -len(".md")]
    return f"{layer.capitalize()} - {stem.replace('-', ' ')}"


def requirement_line(token: str, inv: Inventory) -> str:
    meta = inv.requirement_meta(token) or {}
    must = " (MUST)" if meta.get("must") else ""
    return f"`{token}` - {meta.get('title', '')} (SRS section {meta.get('srs_section', '?')}{must})"


def facet_line(token: str, inv: Inventory) -> str:
    parsed = inv.facet_meta(token)
    if not parsed:
        return f"`{token}`"
    family, item = parsed
    group = f", {item['group']}" if item.get("group") else ""
    requires = item.get("requires") or []
    suffix = f" (requires {', '.join(sorted(requires))})" if requires else ""
    return (
        f"`{token}` - {item.get('title', '')} "
        f"[{family}{group}, SRS section {item.get('srs_section', '?')}]{suffix}"
    )


def case_block(case: dict, inv: Inventory, up: str) -> str:
    cid = case["id"]
    pair = case.get("pair") or "-"
    parts = [
        f'<a id="{anchor(cid)}"></a>',
        "",
        f"### `{cid}` - {case['title']}",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Suite | `{case['suite']}` |",
        f"| Layer | {case['layer']} |",
        f"| Environment | {case['environment']} |",
        f"| Priority | {case['priority']} |",
        f"| Gate | {case['gate']} |",
        f"| Basis | {case['basis']} |",
        f"| Pair | {('`' + pair + '`') if pair != '-' else '-'} |",
        f"| Source module | `sources/{case['_module']}.py` |",
        f"| Design status | `{DEFAULT_STATUS}` |",
        "",
    ]

    requirement_tokens = case.get("requirements") or []
    parts.append("**Provenance**")
    parts.append("")
    if requirement_tokens:
        parts.append("\n".join(f"- {requirement_line(token, inv)}" for token in requirement_tokens))
    else:
        parts.append("- no requirement ID declared (extension probe)")
    parts.append("")

    parts.append(f"**Real-life risk.** {case['risk']}")
    parts.append("")

    facet_tokens = case.get("facets") or []
    if facet_tokens:
        parts.append("**Coverage facets**")
        parts.append("")
        parts.append("\n".join(f"- {facet_line(token, inv)}" for token in facet_tokens))
        parts.append("")

    parts.append("**Preconditions**")
    parts.append("")
    parts.append(numbers(case["preconditions"]))
    parts.append("")

    parts.append("**Inputs** (synthetic test configuration, never production policy)")
    parts.append("")
    parts.append("```json")
    parts.append(json_block(case["inputs"]))
    parts.append("```")
    parts.append("")

    parts.append("**Steps**")
    parts.append("")
    parts.append("| # | Action | Expected |")
    parts.append("|---|---|---|")
    for index, step in enumerate(case["steps"], 1):
        parts.append(f"| {index} | {cell(step['action'])} | {cell(step['expected'])} |")
    parts.append("")

    for label, key in (
        ("Assertions", "assertions"),
        ("Forbidden", "forbidden"),
        ("Evidence to collect (redacted)", "evidence"),
        ("Cleanup", "cleanup"),
    ):
        parts.append(f"**{label}**")
        parts.append("")
        parts.append(bullets(case[key]))
        parts.append("")

    parts.append(f"**Automation seam.** {case['automation']}")
    parts.append("")

    parts.append("**Prerequisites**")
    parts.append("")
    prerequisites = case.get("prerequisites") or []
    parts.append(bullets(prerequisites) if prerequisites else "- none beyond the offline toolchain")
    parts.append("")

    parts.append("**References**")
    parts.append("")
    parts.append(bullets(f"`{reference}`" for reference in case["references"]))
    parts.append("")

    fixtures = case.get("fixtures") or []
    parts.append("**Fixtures**")
    parts.append("")
    parts.append(
        bullets(f"[`{fixture}`]({up}{fixture})" for fixture in fixtures) if fixtures else "- none"
    )
    parts.append("")

    parts.append(
        "**Status.** `"
        + DEFAULT_STATUS
        + "` - descriptive acceptance specification; the repository runtime is not exercised by this generated document, so nothing here has been executed. Machine-readable copy: "
        f"[`{up}{SCENARIO_DIR}/{cid}.json`]({up}{SCENARIO_DIR}/{cid}.json)."
    )
    parts.append("")
    return "\n".join(parts)


def render_suite(suite: str, cases: list, inv: Inventory) -> str:
    up = "../" * (len(suite.split("/")) - 1)
    layer = suite.split("/")[0]
    lines = [
        marker(),
        "",
        f"# {suite_title(suite)}",
        "",
        f"`{suite}` - layer `{layer}` - {len(cases)} case(s) - design status `{DEFAULT_STATUS}` throughout.",
        "",
        "Generated from " + ", ".join(f"`sources/{name}.py`" for name in MODULES) + ". "
        "Do not edit this file: change the source module and re-run `python testcases/_generate.py`.",
        "",
        "## Case index",
        "",
        "| Case ID | Environment | Priority | Gate | Title |",
        "|---|---|---|---|---|",
    ]
    for case in cases:
        lines.append(
            f"| [`{case['id']}`](#{anchor(case['id'])}) | {case['environment']} | {case['priority']} "
            f"| {case['gate']} | {cell(case['title'])} |"
        )
    lines.extend(["", "## Cases", ""])
    for case in cases:
        lines.append(case_block(case, inv, up))
    return "\n".join(lines).rstrip() + "\n"


def render_readme(inv: Inventory, cases: list, fixtures: dict, baseline_info: dict, coverage: dict) -> str:
    by_layer = Counter(case["layer"] for case in cases)
    by_env = Counter(case["environment"] for case in cases)
    coverage_line = ", ".join(f"{count} {layer}" for layer, count in sorted(by_layer.items()))
    return "\n".join(
        [
            marker(),
            "",
            "# Testcases - risk-based acceptance specifications",
            "",
            f"{len(cases)} cases generated from the SRS v0.1 blueprint: {by_env['offline']} offline, "
            f"{by_env['live']} live ({coverage_line}). Every entry is a written acceptance specification "
            "for a future system under test - not an executable test, not a mock echo and not a "
            "source-code inspection.",
            "",
            "## Honest status",
            "",
            f"- **The repository includes an API, a worker with Care/Sales/Marketing agents, two consoles, and PostgreSQL migrations.** Nothing has been executed by this generator; the "
            f"default recorded status for these acceptance specifications is `{DEFAULT_STATUS}`.",
            "- This generator never records `PASS`. A successful generation run proves document integrity, "
            "reference validity and coverage bookkeeping - never system behaviour.",
            "- Status vocabulary: " + ", ".join(f"`{item}`" for item in STATUS_VOCAB) + ".",
            "- `SKIP_ASM_001` when the approved connector lock is absent, `SKIP_UNIMPLEMENTED` when the "
            "runtime is missing, `BLOCKED_PREREQUISITE` when a sandbox feature or policy lock is "
            "unavailable. A missing prerequisite is never `PASS`.",
            "",
            "## What coverage does and does not mean",
            "",
            "- Coverage here means **traceability**: every case names exact requirement tokens and coverage "
            "facets, and the generator refuses to write output when a mandatory facet token, a baseline case "
            "ID or an offline/live E2E counterpart is missing.",
            "- Matching is exact-token set membership, never substring matching, so no ID can silently stand "
            "in for another.",
            "- This is **not** an exhaustive claim over the whole checklist surface. Failure and boundary "
            "probes live in the unit and integration layers; E2E is limited to critical journeys.",
            f"- Baseline preservation: {baseline_info['preserved']}/{baseline_info['count']} current case IDs "
            "are retained exactly once, with mixed-case and dotted IDs preserved verbatim. An older draft "
            "mentioned 343 IDs; that set is not recoverable or verifiable here and is therefore not claimed.",
            "",
            "## Layout",
            "",
            "```text",
            "testcases/",
            "|-- README.md              this guide (generated)",
            "|-- TRACEABILITY.md        case -> requirement/facet index (generated)",
            "|-- COVERAGE.md            requirement/facet -> cases, gaps (generated)",
            "|-- manifest.json          machine-readable counts, hashes and coverage (generated)",
            "|-- _generate.py           generator + validator (hand-written)",
            "|-- sources/               hand-written case sources",
            "|   |-- requirements.json  requirement inventory + mandatory facet tokens",
            f"|   |-- baseline-ids.json  {baseline_info['count']} current case IDs that must all survive",
            "|   |-- business.py        skills, sales and care, pilots, offline+live E2E",
            "|   |-- governance.py      authority / rules / NFR / ASM / command center / KPI / gates",
            "|   `-- platform.py        knowledge, entities, memory, API, C360, case FSM",
            "|-- platform/              knowledge+memory and entity coverage maps (generated)",
            "|-- fixtures/",
            "|   |-- README.md          fixture ownership, synthetic data, cleanup rules (generated)",
            "|   |-- offline/*.json     deterministic offline system-of-record (from source FIXTURES)",
            "|   |-- live/env.example   secret-free sandbox placeholder (generated)",
            "|   |-- live/README.md     live sandbox guide (generated)",
            "|   `-- scenarios/*.json   per-case machine-readable spec copies (generated)",
            "|-- unit/  integration/  e2e/  governance/    case documents (generated)",
            "`-- .gitignore             keeps local sandbox env and run results out of git",
            "```",
            "",
            "## Strategy",
            "",
            "```text",
            "        E2E (e2e/offline.md + e2e/live.md)   few, critical complete journeys",
            "     Integration (API, C360, FSM, command center, routing)",
            "  Unit (skills, authority, business rules, knowledge, entities)",
            "```",
            "",
            "- Many fast isolated cases carry the failure, boundary and negative load; E2E carries complete "
            "outcomes with evidence.",
            "- Every E2E case is paired offline/live with an identical requirement set, so the same observable "
            "contract is specified twice: against intercepted fixtures and against an approved sandbox.",
            "- Cases are independent: each owns its namespace (`run_id` / `case_id` / `worker`), its setup and "
            "its cleanup. Waits are condition or deadline based, never fixed sleeps.",
            "- Core policy, routing and evidence paths are never replaced by stubbed results.",
            "",
            "## Offline vs live",
            "",
            "| | Offline | Live |",
            "|---|---|---|",
            "| Data | [`fixtures/offline/`](fixtures/offline/) JSON system-of-record mocks | sandbox records created per case |",
            "| Network | all vendor HTTP intercepted | approved sandbox endpoints only, never production |",
            "| Identity | synthetic handles (`cust-a`, `SKU-OK`) | sandbox IDs mapped through gitignored `fixtures/live/env.local` |",
            "| Evidence | mock/provider call logs | provider receipts plus audit records |",
            "| Gate | none | approved ASM-001 connector lock, sandbox allowlist, approved recipients |",
            "| Waiting | fixture/mock condition | provider webhook or status condition |",
            "| Cleanup | reset namespaced mock state | retire only what the case created; keep immutable receipts |",
            "",
            "## Regenerating",
            "",
            "```bash",
            "python testcases/_generate.py            # validate, then write docs, fixtures and manifest",
            "python testcases/_generate.py --check    # validate and compare with disk; writes nothing",
            "```",
            "",
            "Python 3 standard library only, no network: these case documents are specifications, and no runtime test "
            "was executed by the generator to produce them. Generation validates first and "
            "writes only after every check passes, each file through a temporary file plus an atomic replace, "
            "and it never rewrites `_generate.py`, `sources/*.py`, `sources/requirements.json` or "
            "`sources/baseline-ids.json`. Output is deterministic: regenerating without source changes leaves "
            "the tree byte-identical, and no timestamp or run state is embedded anywhere. `manifest.json` "
            "pins the SHA-256 of every input (SRS, inventory, baseline, source modules), and `--check` "
            "re-reads the generated files and the manifest and exits non-zero on validation errors, missing "
            "or stale output, and unexpected leftover generated files (for example an obsolete catalogue "
            "document). Errors are reported per case with the owning source module and position.",
            "",
            "## Validation performed before any write",
            "",
            "Required field types and detail minima (at least 3 named steps, 3 assertions, 2 forbidden results, "
            "2 evidence items, 1 cleanup step, 2 preconditions, non-empty synthetic `inputs`, concrete `risk` "
            "and `automation` seam); unique case IDs with all baseline IDs retained exactly once; layer/suite "
            "agreement; valid environment, priority, gate and basis; reference paths that exist in the "
            "repository; requirement and facet tokens declared in `sources/requirements.json`; fixtures that "
            "exist in the merged source `FIXTURES`; complete mandatory facet coverage; every TC-E2E and PILOT "
            "criterion in both environments; symmetric offline/live E2E pairs with identical requirement sets "
            "and live prerequisites naming the approved ASM-001 lock.",
            "",
            "Unclaimed requirement IDs are reported as coverage gaps in [`COVERAGE.md`](COVERAGE.md) and in "
            "`manifest.json`; unclaimed mandatory facet tokens are hard errors.",
            "",
            "## Secrets, results and receipts",
            "",
            "- [`fixtures/live/env.example`](fixtures/live/env.example) is a placeholder. Its presence is "
            "**not** approval: a live run still requires the approved ASM-001 lock and an allowlist.",
            "- Real sandbox values belong in `fixtures/live/env.local` or the process environment, both kept "
            "out of git by [`.gitignore`](.gitignore). The generator never reads, writes or deletes local env "
            "files.",
            "- Run results, receipts and scratch evidence stay in `results/`, which is gitignored. Sandbox "
            "receipts kept for audit are immutable: a case deletes only the records it created itself.",
            "- Never mark a live case `PASS` without provider evidence, and never delete a sent message to "
            "pretend it was not sent.",
            "",
            "## Indexes",
            "",
            f"- [`TRACEABILITY.md`](TRACEABILITY.md) - all {len(cases)} cases with suite, environment, layer, "
            "priority, gate, basis, pair and requirement tokens.",
            "- [`COVERAGE.md`](COVERAGE.md) - reverse map from every requirement and facet token to its cases, "
            "plus the remaining gaps.",
            f"- [`manifest.json`](manifest.json) - machine-readable counts, SHA-256 of every generator input "
            f"and coverage ({len(fixtures)} fixture files from source modules).",
            f"- [`{PLATFORM_KNOWLEDGE_DOC}`]({PLATFORM_KNOWLEDGE_DOC}) - knowledge base (section 10) and memory "
            "(section 16) facet map.",
            f"- [`{PLATFORM_ENTITIES_DOC}`]({PLATFORM_ENTITIES_DOC}) - canonical entity (section 14) facet map.",
            f"- [`{REQUIREMENTS_REL}`]({REQUIREMENTS_REL}) - requirement inventory "
            f"({len(inv.requirements)} requirement IDs, {len(inv.aliases)} section aliases, "
            f"{len(inv.mandatory_facet_tokens())} mandatory facet tokens).",
            f"- [`../{SRS_REL}`](../{SRS_REL}) - authoritative SRS v0.1 (AI-REV-SRS-001).",
            "",
        ]
    ).rstrip() + "\n"

def render_traceability(cases: list, inv: Inventory, baseline_info: dict, pairs: dict) -> str:
    by_id = {case["id"]: case for case in cases if isinstance(case.get("id"), str)}
    lines = [
        marker(),
        "",
        "# Traceability - case index",
        "",
        f"{len(cases)} cases, every ID taken verbatim from the source modules (mixed case and dots preserved; "
        "no ID normalisation anywhere). One row per case; the reverse direction is in "
        "[`COVERAGE.md`](COVERAGE.md). Nothing in this file is evidence of execution: the repository "
        f"runtime is not exercised by generation and every case stays `{DEFAULT_STATUS}`.",
        "",
        "## Baseline preservation",
        "",
        f"- Current baseline: {baseline_info['count']} case IDs from "
        f"[`{BASELINE_REL}`]({BASELINE_REL}) (a snapshot taken before this generation).",
        f"- Preserved exactly once: {baseline_info['preserved']}. Missing: "
        f"{len(baseline_info['missing'])}. Duplicated: {len(baseline_info['duplicated'])}.",
        f"- New descriptive case IDs added by this generation: {len(baseline_info['new_case_ids'])}.",
        "- Every baseline ID below resolves to a case document; IDs are matched as exact strings, so "
        "`E2E-LIVE-001` is never satisfied by `E2E-LIVE-0010` and `INT-FR-CS-001-OTHERS` is never satisfied "
        "by `INT-FR-CS-001-OTHER`.",
        "- An older draft of this suite mentioned 343 IDs. That set cannot be recovered or verified from the "
        "repository, so this document claims only the current baseline snapshot; no historic ID is invented "
        "and no unavailable set is claimed as preserved.",
        "",
        "## Baseline ID placement",
        "",
        "| Baseline case ID | Suite | Layer | Environment |",
        "|---|---|---|---|",
    ]
    for cid in baseline_info.get("order") or sorted(by_id):
        case = by_id.get(cid)
        if case is None:
            lines.append(f"| `{cid}` | **MISSING - no case produces this ID** | - | - |")
            continue
        lines.append(
            f"| [`{cid}`]({case['suite']}#{anchor(cid)}) | `{case['suite']}` | {case['layer']} "
            f"| {case['environment']} |"
        )

    lines.extend(
        [
            "",
            "## Cases",
            "",
            "| Case ID | Suite | Layer | Env | Priority | Gate | Basis | Pair | Requirements | Facets |",
            "|---|---|---|---|---|---|---|---|---|---|",
        ]
    )
    for case in sorted(cases, key=lambda item: (item["suite"], item["id"])):
        requirements = case.get("requirements") or []
        facets = case.get("facets") or []
        pair = case.get("pair") or "-"
        lines.append(
            f"| [`{case['id']}`]({case['suite']}#{anchor(case['id'])}) | `{case['suite']}` "
            f"| {case['layer']} | {case['environment']} | {case['priority']} | {case['gate']} "
            f"| {case['basis']} | {('`' + pair + '`') if pair != '-' else '-'} "
            f"| {cell(', '.join(f'`{token}`' for token in requirements)) or '-'} "
            f"| {cell(', '.join(f'`{token}`' for token in facets)) or '-'} |"
        )

    lines.extend(
        [
            "",
            "## Offline/live pairing",
            "",
            f"{pairs['paired_e2e_cases']}/{pairs['e2e_cases']} e2e case(s) declare a counterpart; the partner "
            "must be an e2e case in the opposite environment, must point back, and must declare the same "
            f"requirements and facets. Unsymmetrical pair relations: {len(pairs['asymmetric'])}. "
            f"Unpaired e2e cases: {len(pairs['unpaired'])}.",
            "",
            "| E2E case | Counterpart |",
            "|---|---|",
        ]
    )
    for cid, partner in sorted((pairs.get("relations") or {}).items()):
        lines.append(f"| `{cid}` | `{partner}` |")

    lines.extend(
        [
            "",
            "## Documents",
            "",
            "| Suite | Layer | Cases |",
            "|---|---|---|",
        ]
    )
    per_suite = Counter(case["suite"] for case in cases)
    for suite in sorted(per_suite):
        lines.append(f"| [`{suite}`]({suite}) | {suite.split('/')[0]} | {per_suite[suite]} |")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_coverage(inv: Inventory, cases: list, coverage: dict, both_env: dict) -> str:
    requirement_cases = coverage["requirement_cases"]
    facet_cases = coverage["facet_cases"]
    lines = [
        marker(),
        "",
        "# Coverage - reverse map",
        "",
        "Membership below is **exact token set membership**, never substring matching: a case covers `SRS-02` "
        "only if it declares `SRS-02`, and `TC-E2E-001` is never satisfied by `TC-E2E-0010`. Coverage is a "
        "traceability statement about specifications, not evidence that anything has been executed: every case "
        f"is `{DEFAULT_STATUS}`.",
        "",
        "## Requirement reverse map",
        "",
        "| Requirement | Kind | Cases | Case IDs |",
        "|---|---|---|---|",
    ]
    for token in sorted(inv.requirements):
        meta = inv.requirements[token]
        ids = requirement_cases.get(token, [])
        listed = ", ".join(f"`{cid}`" for cid in ids) if ids else "**GAP - no case claims this requirement**"
        lines.append(f"| `{token}` | {meta.get('kind', '')} | {len(ids)} | {listed} |")
    lines.extend(["", "## Section aliases", "", "| Alias | Cases | Case IDs |", "|---|---|---|"])
    for token in sorted(inv.aliases):
        ids = requirement_cases.get(token, [])
        listed = ", ".join(f"`{cid}`" for cid in ids) if ids else "**GAP - no case claims this section obligation**"
        lines.append(f"| `{token}` | {len(ids)} | {listed} |")

    lines.extend(["", "## Facet coverage", ""])
    for family in sorted(inv.facets):
        spec = inv.facets[family]
        tokens = sorted(spec["items"])
        covered = sum(1 for token in tokens if facet_cases.get(f"{family}:{token}"))
        lines.append(f"### {family} - {covered}/{len(tokens)} covered")
        lines.append("")
        lines.append(f"{spec['description']} (SRS section {spec['srs_section']}.)")
        lines.append("")
        lines.append("| Token | Requires | Cases | Case IDs |")
        lines.append("|---|---|---|---|")
        for token in tokens:
            full = f"{family}:{token}"
            item = spec["items"][token]
            ids = facet_cases.get(full, [])
            listed = ", ".join(f"`{cid}`" for cid in ids) if ids else "**GAP**"
            requires = ", ".join(f"`{req}`" for req in (item.get("requires") or [])) or "-"
            lines.append(f"| `{token}` | {requires} | {len(ids)} | {listed} |")
        lines.append("")

    lines.extend(
        [
            "## Both environments (system acceptance criteria and pilots)",
            "",
            "| Criterion | Offline e2e cases | Live e2e cases |",
            "|---|---|---|",
        ]
    )
    for token in sorted(both_env):
        entry = both_env[token]
        offline = ", ".join(f"`{cid}`" for cid in entry["offline"]) or "**GAP**"
        live = ", ".join(f"`{cid}`" for cid in entry["live"]) or "**GAP**"
        lines.append(f"| `{token}` | {offline} | {live} |")

    lines.extend(["", "## Remaining gaps", ""])
    if coverage["facet_gaps"]:
        lines.append("Mandatory facet tokens with no case (these are hard errors and must be empty):")
        lines.append("")
        lines.extend(f"- `{token}`" for token in coverage["facet_gaps"])
    else:
        lines.append("- No mandatory facet token is uncovered.")
    lines.append("")
    if coverage["requirement_gaps"]:
        lines.append(
            "Requirement or alias tokens with no case (reported, not fatal: a token may be carried by a "
            "section-level obligation or be planned for a later gate):"
        )
        lines.append("")
        lines.extend(f"- `{token}`" for token in coverage["requirement_gaps"])
    else:
        lines.append("- Every requirement ID and section alias is claimed by at least one case.")
    lines.extend(
        [
            "",
            "## Design status",
            "",
            f"- Total cases: {len(cases)}. Every case is `{DEFAULT_STATUS}`: the specifications exist, the "
            "system under test does not.",
            "- Gaps above are documented rather than hidden. They are not evidence of coverage and not a claim "
            "that the checklist surface is exhaustively covered.",
            "",
            "## Related maps",
            "",
            f"- [`{PLATFORM_KNOWLEDGE_DOC}`]({PLATFORM_KNOWLEDGE_DOC}) - knowledge base (section 10) and AI "
            "memory (section 16) tokens with their covering cases.",
            f"- [`{PLATFORM_ENTITIES_DOC}`]({PLATFORM_ENTITIES_DOC}) - canonical entity (section 14) tokens "
            "with their covering cases.",
            "- [`TRACEABILITY.md`](TRACEABILITY.md) - the forward direction: every case with its suite, "
            "environment, pair and tokens.",
            "- [`manifest.json`](manifest.json) - the same counts, the coverage gaps and the SHA-256 of every "
            "generator input in machine-readable form.",
            "",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def render_platform_facets(inv: Inventory, cases: list, coverage: dict, title: str, blurb: str, families) -> str:
    """Derived coverage map for one group of facet families (never a case document)."""
    facet_cases = coverage["facet_cases"]
    lines = [
        marker(),
        "",
        f"# {title}",
        "",
        blurb,
        "",
        "This is a **derived coverage map**, not a case document and not evidence of execution: it is "
        "rendered from the coverage facets the cases declare in `sources/{business,governance,platform}.py` "
        f"against `{REQUIREMENTS_REL}`. No case declares a suite under `{PLATFORM_DIR}/`. Every entry is "
        f"`{DEFAULT_STATUS}` - the specifications exist, the system under test does not.",
        "",
    ]
    for family in families:
        spec = inv.facets.get(family)
        if spec is None:
            continue
        tokens = sorted(spec["items"])
        covered = sum(1 for token in tokens if facet_cases.get(f"{family}:{token}"))
        lines.append(f"## {family} - {covered}/{len(tokens)} covered")
        lines.append("")
        lines.append(f"{spec['description']} (SRS section {spec['srs_section']}.)")
        lines.append("")
        lines.append("| Token | Title | Group | Requires | Cases | Case IDs |")
        lines.append("|---|---|---|---|---|---|")
        for token in tokens:
            full = f"{family}:{token}"
            item = spec["items"][token]
            ids = facet_cases.get(full, [])
            listed = ", ".join(f"`{cid}`" for cid in ids) if ids else "**GAP - no case declares this facet**"
            requires = ", ".join(f"`{req}`" for req in (item.get("requires") or [])) or "-"
            lines.append(
                f"| `{token}` | {cell(item.get('title', ''))} | {cell(item.get('group', ''))} | "
                f"{requires} | {len(ids)} | {listed} |"
            )
        lines.append("")
        gaps = [token for token in tokens if not facet_cases.get(f"{family}:{token}")]
        if gaps:
            lines.append("Uncovered tokens in this family (a mandatory facet gap is a hard generator error):")
            lines.append("")
            lines.extend(f"- `{family}:{token}`" for token in gaps)
        else:
            lines.append("No uncovered token in this family.")
        lines.append("")
    lines.extend(
        [
            "## Reading this map",
            "",
            "- Coverage means traceability: an exact-token set membership between a facet token and the "
            "cases that declare it, never substring matching.",
            "- A token being covered means the checklist surface is *specified somewhere*; it is not a claim "
            "that the behaviour has been observed, and this suite records no `PASS` for behaviour the generator "
            "has not executed.",
            f"- The full reverse map for every requirement and facet family is in [`../COVERAGE.md`](../COVERAGE.md); "
            f"per-case detail is in the case documents under `unit/`, `integration/`, `e2e/` and `governance/`.",
            "",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def render_platform_knowledge_memory(inv: Inventory, cases: list, coverage: dict) -> str:
    return render_platform_facets(
        inv,
        cases,
        coverage,
        "Platform - knowledge base and memory coverage",
        "Which cases exercise the required knowledge base paths (SRS section 10) and which exercise each "
        "AI memory store (section 16). Knowledge coverage is only meaningful when a case reads the real "
        "corpus entry with its version and provenance and answers from it, so a knowledge path claimed by "
        "a case that never queries it is not coverage.",
        ("kb", "memory"),
    )


def render_platform_entities(inv: Inventory, cases: list, coverage: dict) -> str:
    return render_platform_facets(
        inv,
        cases,
        coverage,
        "Platform - canonical entity coverage",
        "Which cases exercise each of the canonical entities of the core data model (SRS section 14). "
        "Entity coverage means consumer-contract behaviour - create/read/update invariants, tenancy and "
        "identity isolation, retention - not the mere presence of a table or column definition.",
        ("entity",),
    )


def arrange(counter: Counter, keys=None) -> dict:
    if keys is None:
        keys = sorted(counter)
    return {key: counter[key] for key in keys if counter[key]}


def render_manifest(
    inv, cases, fixtures, fixture_owners_map, baseline_info, coverage, pairs, both_env, problems, documents
) -> str:
    requirement_cases = coverage["requirement_cases"]
    facet_cases = coverage["facet_cases"]
    manifest = OrderedDict(
        [
            ("schema", "testcases.manifest/1"),
            ("generator", GENERATOR_REL),
            ("srs_source", SRS_REL),
            ("requirements_source", REQUIREMENTS_REL),
            ("baseline_source", BASELINE_REL),
            ("case_source_modules", [f"sources/{name}.py" for name in MODULES]),
            (
                "input_hashes",
                OrderedDict(
                    [
                        ("algorithm", "sha256"),
                        (
                            "note",
                            "SHA-256 of every generator input with CRLF normalized to LF; "
                            "--check re-reads them so a review can pin exactly which sources were rendered.",
                        ),
                        ("files", input_hashes()),
                    ]
                ),
            ),
            (
                "design_status",
                OrderedDict(
                    [
                        ("default", DEFAULT_STATUS),
                        ("vocabulary", STATUS_VOCAB),
                        ("runtime_available", True),
                        ("pass_recorded", False),
                        ("source_documents_are_specifications", True),
                        (
                            "note",
                            "The repository includes runtime, but no runtime test was executed by the generator. The case "
                            "documents are specifications. Generation proves document integrity and "
                            "traceability only; the generator never records PASS.",
                        ),
                    ]
                ),
            ),
            (
                "counts",
                OrderedDict(
                    [
                        ("cases", len(cases)),
                        ("by_layer", arrange(Counter(case["layer"] for case in cases), list(LAYER_DIRS))),
                        ("by_environment", arrange(Counter(case["environment"] for case in cases), list(ENVIRONMENTS))),
                        ("by_priority", arrange(Counter(case["priority"] for case in cases), list(PRIORITIES))),
                        ("by_gate", arrange(Counter(case["gate"] for case in cases), list(GATES))),
                        ("by_basis", arrange(Counter(case["basis"] for case in cases), list(BASES))),
                        ("by_suite", arrange(Counter(case["suite"] for case in cases))),
                        ("by_source_module", arrange(Counter(case["_module"] for case in cases), list(MODULES))),
                    ]
                ),
            ),
            ("baseline", baseline_info),
            (
                "coverage",
                OrderedDict(
                    [
                        (
                            "requirements",
                            OrderedDict(
                                [
                                    ("total", len(requirement_cases)),
                                    ("covered", sum(1 for ids in requirement_cases.values() if ids)),
                                    ("gaps", coverage["requirement_gaps"]),
                                    ("cases_per_token", {t: requirement_cases[t] for t in sorted(requirement_cases)}),
                                ]
                            ),
                        ),
                        (
                            "facets",
                            OrderedDict(
                                [
                                    ("total", len(facet_cases)),
                                    ("covered", sum(1 for ids in facet_cases.values() if ids)),
                                    ("gaps", coverage["facet_gaps"]),
                                    ("cases_per_token", {t: facet_cases[t] for t in sorted(facet_cases)}),
                                ]
                            ),
                        ),
                        ("both_environments", both_env),
                    ]
                ),
            ),
            ("pairs", pairs),
            ("documents", documents),
            ("derived_documents", list(DERIVED_DOCS)),
            (
                "fixtures",
                OrderedDict(
                    [
                        ("source_fixtures", dict(sorted(fixture_owners_map.items()))),
                        ("fixture_count", len(fixtures)),
                        ("generator_fixtures", [LIVE_ENV_EXAMPLE, FIXTURES_GUIDE, LIVE_FIXTURES_GUIDE]),
                        ("scenario_exports", len(cases)),
                    ]
                ),
            ),
            (
                "validation",
                OrderedDict(
                    [
                        ("errors", problems.errors),
                        ("warnings", problems.warnings),
                        ("clean", problems.ok),
                    ]
                ),
            ),
        ]
    )
    return json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"


def render_fixtures_guide(fixture_owners_map: dict) -> str:
    lines = [
        marker(),
        "",
        "# Fixtures",
        "",
        "All fixture data is synthetic test configuration. It is not production data, not an approved policy "
        "and not a KPI baseline (ASM-002..ASM-005 stay unconfirmed until their owners lock them).",
        "",
        "## Offline fixtures",
        "",
        "| Fixture | Owner |",
        "|---|---|",
    ]
    for path, owner in sorted(fixture_owners_map.items()):
        lines.append(f"| `{path}` | `{owner}` |")
    lines.extend(
        [
            "",
            "Rules applied to every offline fixture:",
            "",
            "- Frozen clock `2026-01-15T10:00:00Z`; no fixture reads the wall clock.",
            "- Reserved `.invalid` domains and synthetic logical handles instead of real phone numbers, tokens "
            "or customer data.",
            "- Consent is scoped per channel and purpose; never a wildcard positive. A customer-supplied "
            "`verification_status` payload is not trusted as identity - identity resolves from the "
            "gateway-bound session or the verified identity registry.",
            "- Tenant IDs are fixed example UUIDs; parallel runs are separated by `run_id` / `case_id` / "
            "`worker` namespaces, not by editing fixtures.",
            "- Fixture state is reset by the case that dirtied it; mock ephemeral state is cleared in cleanup.",
            "",
            "## Live fixtures",
            "",
            f"- [`fixtures/live/env.example`]({LIVE_ENV_EXAMPLE.split('/')[-1]}) is a secret-free placeholder and "
            "a checklist, not an approval. Live execution still requires the approved ASM-001 connector lock, "
            "an allowlisted sandbox and approved recipients.",
            "- Real values live in `fixtures/live/env.local` or the process environment. That file is gitignored, "
            "and the generator never creates, reads or overwrites it.",
            f"- See [`fixtures/live/README.md`](live/README.md) for the sandbox workflow.",
            "",
            "## Case exports",
            "",
            "- `fixtures/scenarios/<case id>.json` mirrors one case in machine-readable form (same fields as "
            "the case document: requirements, facets, inputs, steps, assertions, forbidden, evidence, cleanup, "
            "automation, prerequisites, references, fixtures) with `status: NOT_RUN`. It is a specification "
            "export, not a test artifact from a run.",
            "",
            "## Generated, never hand-edited",
            "",
            "Everything in this directory is produced by `python testcases/_generate.py` from the `FIXTURES` "
            "dict of the source modules and the case records, except `env.local` (yours, untracked) and "
            "`results/` (local run artifacts). `--check` reports any file here that the generator does not "
            "produce, and the generator never deletes a file it did not produce.",
            "",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def render_live_guide() -> str:
    return "\n".join(
        [
            marker(),
            "",
            "# Live sandbox fixtures",
            "",
            "Staged sandbox endpoints only - never production. Copy `env.example` to `env.local`, fill it with "
            "sandbox values, and keep it out of git (it is already in `.gitignore`, and the generator will "
            "never write it).",
            "",
            "## Before any live case runs",
            "",
            "1. The ASM-001 connector lock is approved and its path is set in `LIVE_CONNECTORS_LOCK`.",
            "2. The sandbox hosts are on the approved allowlist and the recipients are approved sandbox "
            "identities.",
            "3. Credentials come from the environment, never from a tracked file.",
            "4. Logical fixture handles (`cust-a`, `SKU-OK`) are mapped to sandbox IDs through `env.local`.",
            "",
            "If the lock is missing every live case is `SKIP_ASM_001`; an unsupported sandbox feature or an "
            "unlocked policy is `BLOCKED_PREREQUISITE`. Neither is `PASS`, and neither may be reported as one.",
            "",
            "## Identity and data",
            "",
            "- Each case creates its own sandbox records with a unique `run_id` and never shares a session "
            "with another case.",
            "- Consent is checked per channel and purpose before any outbound message; a denied action needs no "
            "provider receipt - the zero-call audit record plus the provider test sink is the oracle.",
            "",
            "## Cleanup, receipts and immutability",
            "",
            "- Cleanup retires only what the case created, through the supported sandbox APIs.",
            "- Audit records and provider receipts are immutable: never delete a message that was actually sent "
            "to pretend it was not, and never remove pre-existing sandbox records.",
            "- Artifacts that cannot be deleted are reported instead of hidden.",
            "- Local run results, receipts and scratch evidence go to `results/`, which is gitignored.",
            "",
        ]
    ).rstrip() + "\n"


def render_env_example() -> str:
    return "\n".join(
        [
            "# Live sandbox placeholders for testcases/live/*.example - NOT a credential file and NOT an",
            "# approval. Copy to env.local (gitignored) and fill with approved sandbox values.",
            "#",
            "# Required before any live case: an approved ASM-001 connector lock. Without it, live cases are",
            "# SKIP_ASM_001. Nothing here is validated by the generator: the file existing proves nothing.",
            "",
            "# ASM-001 approved connector lock (path to the owner-approved lock document)",
            "LIVE_CONNECTORS_LOCK=",
            "",
            "# Sandbox endpoints and tenant",
            "LIVE_BASE_URL=https://sandbox.api.invalid",
            "LIVE_ERP_BASE_URL=https://sandbox.erp.invalid",
            "LIVE_TENANT_ID=",
            "LIVE_ALLOWLIST_HOSTS=sandbox.api.invalid,sandbox.erp.invalid",
            "",
            "# Credentials are read from the process environment, never from this file",
            "# LIVE_ERP_TOKEN=  (set in the shell, do not store here)",
            "",
            "# Approved sandbox identities (logical fixture handle -> sandbox id)",
            "LIVE_CUSTOMER_A_SANDBOX_ID=",
            "LIVE_CUSTOMER_B_SANDBOX_ID=",
            "LIVE_CUSTOMER_A_CONTACT=sandbox-a@example.invalid",
            "LIVE_CUSTOMER_B_CONTACT=sandbox-b@example.invalid",
            "LIVE_SKU_OK=",
            "LIVE_SKU_ZERO=",
            "LIVE_ORDER_A=",
            "LIVE_ORDER_B=",
            "",
            "# Channel used by live journeys (API-003 connector names)",
            "LIVE_CHAT_CHANNEL=WEB_APP_CHAT",
            "",
            "# Local results/receipts directory; gitignored, never committed",
            "LIVE_RESULTS_DIR=results/",
            "",
            "# Every live case creates its own records under a unique run id and deletes only those in cleanup.",
            "",
        ]
    )


def scenario_record(case: dict) -> OrderedDict:
    return OrderedDict(
        [
            ("id", case["id"]),
            ("title", case["title"]),
            ("document", case["suite"]),
            ("layer", case["layer"]),
            ("environment", case["environment"]),
            ("priority", case["priority"]),
            ("gate", case["gate"]),
            ("basis", case["basis"]),
            ("pair", case.get("pair")),
            ("status", DEFAULT_STATUS),
            ("source_module", f"sources/{case['_module']}.py"),
            ("requirements", case["requirements"]),
            ("facets", case["facets"]),
            ("risk", case["risk"]),
            ("preconditions", case["preconditions"]),
            ("inputs", case["inputs"]),
            ("steps", case["steps"]),
            ("assertions", case["assertions"]),
            ("forbidden", case["forbidden"]),
            ("evidence", case["evidence"]),
            ("cleanup", case["cleanup"]),
            ("automation", case["automation"]),
            ("prerequisites", case["prerequisites"]),
            ("references", case["references"]),
            ("fixtures", case["fixtures"]),
            ("srs_source", SRS_REL),
            ("generator", GENERATOR_REL),
            (
                "note",
                "Generated acceptance specification. Plain specification, not an executable test; "
                "the repository runtime is not executed while generating it, so the status is NOT_RUN.",
            ),
        ]
    )
